/* ======================================================================
   N3 GOI — Mimi Kara Oboeru N3 từ vựng
   Dữ liệu từ vựng. Mỗi từ:
     i: số thứ tự trong sách (1..835)
     u: unit (1..11)
     s: step (mốc CD / nhóm học)
     r: cách đọc (hiragana)
     w: từ hiển thị (kanji hoặc kana)
     v: nghĩa tiếng Việt (do mình dịch — sách gốc chỉ có Anh/Trung/Hàn)
     e: nghĩa tiếng Anh (tham khảo, lấy từ sách)
     p: loại từ  n=danh từ  v=động từ(suru)  a=tính từ  adv=phó từ  k=katakana
   ====================================================================== */
window.N3DATA = {
  units: [
    { u:1,  name:"名詞 A",   vi:"Danh từ A",   range:[1,120],   p:"n"   },
    { u:2,  name:"動詞 A",   vi:"Động từ A",   range:[121,258], p:"v"   },
    { u:3,  name:"形容詞 A", vi:"Tính từ A",   range:[259,310], p:"a"   },
    { u:4,  name:"名詞 B",   vi:"Danh từ B",   range:[311,410], p:"n"   },
    { u:5,  name:"動詞 B",   vi:"Động từ B",   range:[411,510], p:"v"   },
    { u:6,  name:"カタカナ A", vi:"Katakana A", range:[511,550], p:"k"   },
    { u:7,  name:"形容詞 B", vi:"Tính từ B",   range:[551,590], p:"a"   },
    { u:8,  name:"副詞 A",   vi:"Phó từ A",    range:[591,635], p:"adv" },
    { u:9,  name:"名詞 C",   vi:"Danh từ C",   range:[636,715], p:"n"   },
    { u:10, name:"動詞 C",   vi:"Động từ C",   range:[716,795], p:"v"   },
    { u:11, name:"カタカナ B", vi:"Katakana B", range:[796,835], p:"k"   }
  ],
  words: [
    {i:1,u:1,s:1,r:"だんせい",w:"男性",v:"đàn ông, nam giới",e:"man",p:"n"},
    {i:2,u:1,s:1,r:"じょせい",w:"女性",v:"phụ nữ, nữ giới",e:"woman",p:"n"},
    {i:3,u:1,s:1,r:"こうれい",w:"高齢",v:"tuổi cao, cao tuổi",e:"old age",p:"n"},
    {i:4,u:1,s:1,r:"としうえ",w:"年上",v:"lớn tuổi hơn, người hơn tuổi",e:"elder",p:"n"},
    {i:5,u:1,s:1,r:"めうえ",w:"目上",v:"bề trên, người trên (cấp/tuổi)",e:"superior",p:"n"},
    {i:6,u:1,s:1,r:"せんぱい",w:"先輩",v:"tiền bối, đàn anh/chị",e:"senior",p:"n"},
    {i:7,u:1,s:1,r:"こうはい",w:"後輩",v:"hậu bối, đàn em",e:"junior",p:"n"},
    {i:8,u:1,s:1,r:"じょうし",w:"上司",v:"cấp trên, sếp",e:"boss",p:"n"},
    {i:9,u:1,s:1,r:"あいて",w:"相手",v:"đối phương, đối tác",e:"other person, opponent",p:"n"},
    {i:10,u:1,s:1,r:"しりあい",w:"知り合い",v:"người quen",e:"acquaintance",p:"n"},
    {i:11,u:1,s:1,r:"ゆうじん",w:"友人",v:"bạn bè, bạn",e:"friend",p:"n"},
    {i:12,u:1,s:1,r:"なか",w:"仲",v:"quan hệ, mối quan hệ (giữa người với người)",e:"relations",p:"n"},
    {i:13,u:1,s:1,r:"せいねんがっぴ",w:"生年月日",v:"ngày tháng năm sinh",e:"date of birth",p:"n"},
    {i:14,u:1,s:1,r:"たんじょう",w:"誕生",v:"sự ra đời, sự sinh ra",e:"birth",p:"v"},
    {i:15,u:1,s:1,r:"とし",w:"年",v:"năm; tuổi",e:"year, age",p:"n"},
    {i:16,u:1,s:1,r:"しゅっしん",w:"出身",v:"xuất thân, quê quán",e:"origin, homeland",p:"n"},
    {i:17,u:1,s:1,r:"こきょう",w:"故郷",v:"quê hương, cố hương",e:"hometown",p:"n"},
    {i:18,u:1,s:1,r:"せいちょう",w:"成長",v:"sự trưởng thành, sự lớn lên",e:"growth",p:"v"},
    {i:19,u:1,s:1,r:"せいじん",w:"成人",v:"người trưởng thành, thành niên",e:"adult",p:"v"},
    {i:20,u:1,s:1,r:"ごうかく",w:"合格",v:"đỗ, trúng tuyển, đậu",e:"passing, acceptance",p:"v"},
    {i:21,u:1,s:1,r:"しんがく",w:"進学",v:"học lên (cấp cao hơn)",e:"going to a higher school",p:"v"},
    {i:22,u:1,s:1,r:"たいがく",w:"退学",v:"thôi học, bỏ học",e:"dropping out of school",p:"v"},
    {i:23,u:1,s:1,r:"しゅうしょく",w:"就職",v:"xin được việc, đi làm",e:"getting employed",p:"v"},
    {i:24,u:1,s:1,r:"たいしょく",w:"退職",v:"nghỉ việc, từ chức, về hưu",e:"resignation, retirement",p:"v"},
    {i:25,u:1,s:1,r:"しつぎょう",w:"失業",v:"thất nghiệp",e:"unemployment",p:"v"},
    {i:26,u:1,s:1,r:"ざんぎょう",w:"残業",v:"làm thêm giờ, tăng ca",e:"overtime work",p:"v"},
    {i:27,u:1,s:1,r:"せいかつ",w:"生活",v:"cuộc sống, sinh hoạt",e:"life",p:"v"},
    {i:28,u:1,s:1,r:"つうきん",w:"通勤",v:"đi làm (di chuyển tới chỗ làm)",e:"commuting",p:"v"},
    {i:29,u:1,s:1,r:"がくれき",w:"学歴",v:"học vấn, trình độ học vấn",e:"educational background",p:"n"},
    {i:30,u:1,s:1,r:"きゅうりょう",w:"給料",v:"lương, tiền lương",e:"salary, pay",p:"n"},
    {i:31,u:1,s:1,r:"めんせつ",w:"面接",v:"phỏng vấn",e:"interview",p:"v"},
    {i:32,u:1,s:1,r:"きゅうけい",w:"休憩",v:"nghỉ giải lao",e:"break, rest",p:"v"},
    {i:33,u:1,s:1,r:"かんこう",w:"観光",v:"tham quan, du lịch",e:"tourism, sightseeing",p:"v"},
    {i:34,u:1,s:1,r:"きこく",w:"帰国",v:"về nước",e:"returning to one's country",p:"v"},
    {i:35,u:1,s:1,r:"きせい",w:"帰省",v:"về quê",e:"returning to one's hometown",p:"v"},
    {i:36,u:1,s:1,r:"きたく",w:"帰宅",v:"về nhà",e:"going home",p:"v"},
    {i:37,u:1,s:1,r:"さんか",w:"参加",v:"tham gia",e:"participation",p:"v"},
    {i:38,u:1,s:1,r:"しゅっせき",w:"出席",v:"có mặt, tham dự",e:"attendance",p:"v"},
    {i:39,u:1,s:1,r:"けっせき",w:"欠席",v:"vắng mặt",e:"absence",p:"v"},
    {i:40,u:1,s:1,r:"ちこく",w:"遅刻",v:"đến muộn, trễ giờ",e:"arriving late",p:"v"},
    {i:41,u:1,s:1,r:"けしょう",w:"化粧",v:"trang điểm",e:"makeup",p:"v"},
    {i:42,u:1,s:1,r:"けいさん",w:"計算",v:"tính toán, phép tính",e:"calculation",p:"v"},
    {i:43,u:1,s:1,r:"けいかく",w:"計画",v:"kế hoạch, lập kế hoạch",e:"plan",p:"v"},
    {i:44,u:1,s:1,r:"せいこう",w:"成功",v:"thành công",e:"success",p:"v"},
    {i:45,u:1,s:1,r:"しっぱい",w:"失敗",v:"thất bại",e:"failure",p:"v"},
    {i:46,u:1,s:1,r:"じゅんび",w:"準備",v:"chuẩn bị",e:"preparation",p:"v"},
    {i:47,u:1,s:1,r:"せいり",w:"整理",v:"sắp xếp, dọn dẹp, chỉnh lý",e:"organizing, arrangement",p:"v"},
    {i:48,u:1,s:1,r:"ちゅうもん",w:"注文",v:"đặt hàng, gọi món, yêu cầu",e:"order, request",p:"v"},
    {i:49,u:1,s:1,r:"ちょきん",w:"貯金",v:"tiết kiệm, để dành tiền",e:"savings, depositing",p:"v"},
    {i:50,u:1,s:1,r:"てつや",w:"徹夜",v:"thức trắng đêm",e:"staying up all night",p:"v"},
    {i:51,u:1,s:1,r:"ひっこし",w:"引っ越し",v:"chuyển nhà",e:"moving (house)",p:"v"},
    {i:52,u:1,s:1,r:"しんちょう",w:"身長",v:"chiều cao (cơ thể)",e:"body height",p:"n"},
    {i:53,u:1,s:1,r:"たいじゅう",w:"体重",v:"cân nặng",e:"body weight",p:"n"},
    {i:54,u:1,s:1,r:"けが",w:"けが",v:"vết thương, chấn thương",e:"injury",p:"v"},
    {i:55,u:1,s:1,r:"かい",w:"会",v:"hội, buổi họp mặt/tiệc",e:"party, gathering",p:"n"},
    {i:56,u:1,s:1,r:"しゅみ",w:"趣味",v:"sở thích, thú vui",e:"hobby, taste",p:"n"},
    {i:57,u:1,s:1,r:"きょうみ",w:"興味",v:"hứng thú, sự quan tâm",e:"interest",p:"n"},
    {i:58,u:1,s:1,r:"おもいで",w:"思い出",v:"kỷ niệm",e:"memory",p:"n"},
    {i:59,u:1,s:1,r:"じょうだん",w:"冗談",v:"lời nói đùa, chuyện đùa",e:"joke",p:"n"},
    {i:60,u:1,s:1,r:"もくてき",w:"目的",v:"mục đích",e:"purpose",p:"n"},
    {i:61,u:1,s:1,r:"やくそく",w:"約束",v:"lời hứa, cuộc hẹn",e:"promise, appointment",p:"v"},
    {i:62,u:1,s:1,r:"おしゃべり",w:"おしゃべり",v:"nói chuyện phiếm; người lắm lời",e:"chatting, talkative",p:"v"},
    {i:63,u:1,s:1,r:"えんりょ",w:"遠慮",v:"sự e ngại, khách sáo, giữ ý",e:"reserve, refraining",p:"v"},
    {i:64,u:1,s:1,r:"がまん",w:"我慢",v:"chịu đựng, nhẫn nhịn",e:"endurance, patience",p:"v"},
    {i:65,u:1,s:1,r:"めいわく",w:"迷惑",v:"sự phiền toái, làm phiền",e:"nuisance, trouble",p:"v"},
    {i:66,u:1,s:1,r:"きぼう",w:"希望",v:"hy vọng, nguyện vọng",e:"hope, wish",p:"v"},
    {i:67,u:1,s:1,r:"ゆめ",w:"夢",v:"giấc mơ, ước mơ",e:"dream",p:"n"},
    {i:68,u:1,s:1,r:"さんせい",w:"賛成",v:"tán thành, đồng ý",e:"agreement, support",p:"v"},
    {i:69,u:1,s:1,r:"はんたい",w:"反対",v:"phản đối; đối lập, ngược lại",e:"opposite, opposition",p:"v"},
    {i:70,u:1,s:1,r:"そうぞう",w:"想像",v:"tưởng tượng",e:"imagination",p:"v"},
    {i:71,u:1,s:1,r:"どりょく",w:"努力",v:"nỗ lực, cố gắng",e:"effort",p:"v"},
    {i:72,u:1,s:2,r:"たいよう",w:"太陽",v:"mặt trời",e:"sun",p:"n"},
    {i:73,u:1,s:2,r:"ちきゅう",w:"地球",v:"trái đất",e:"earth",p:"n"},
    {i:74,u:1,s:2,r:"おんど",w:"温度",v:"nhiệt độ",e:"temperature",p:"n"},
    {i:75,u:1,s:2,r:"しつど",w:"湿度",v:"độ ẩm",e:"humidity",p:"n"},
    {i:76,u:1,s:2,r:"しっけ",w:"湿気",v:"hơi ẩm, sự ẩm ướt",e:"moisture",p:"n"},
    {i:77,u:1,s:2,r:"つゆ",w:"梅雨",v:"mùa mưa (tsuyu)",e:"rainy season",p:"n"},
    {i:78,u:1,s:2,r:"かび",w:"かび",v:"nấm mốc",e:"mold",p:"n"},
    {i:79,u:1,s:2,r:"だんぼう",w:"暖房",v:"lò sưởi, máy sưởi",e:"heater",p:"n"},
    {i:80,u:1,s:2,r:"かわ",w:"皮",v:"da, vỏ (ngoài)",e:"skin, hide",p:"n"},
    {i:81,u:1,s:2,r:"かん",w:"缶",v:"lon, hộp (kim loại)",e:"can",p:"n"},
    {i:82,u:1,s:2,r:"がめん",w:"画面",v:"màn hình",e:"screen",p:"n"},
    {i:83,u:1,s:2,r:"ばんぐみ",w:"番組",v:"chương trình (TV/phát thanh)",e:"TV/radio program",p:"n"},
    {i:84,u:1,s:2,r:"きじ",w:"記事",v:"bài báo, bài viết",e:"article",p:"n"},
    {i:85,u:1,s:2,r:"きんじょ",w:"近所",v:"hàng xóm, khu lân cận",e:"neighborhood",p:"n"},
    {i:86,u:1,s:2,r:"けいさつ",w:"警察",v:"cảnh sát",e:"police",p:"n"},
    {i:87,u:1,s:2,r:"はんにん",w:"犯人",v:"thủ phạm, kẻ phạm tội",e:"criminal",p:"n"},
    {i:88,u:1,s:2,r:"こぜに",w:"小銭",v:"tiền lẻ",e:"small change",p:"n"},
    {i:89,u:1,s:2,r:"ごちそう",w:"ごちそう",v:"món ngon; sự chiêu đãi",e:"feast, treating to a meal",p:"v"},
    {i:90,u:1,s:2,r:"さくしゃ",w:"作者",v:"tác giả",e:"writer, artist",p:"n"},
    {i:91,u:1,s:2,r:"さくひん",w:"作品",v:"tác phẩm",e:"work (of art)",p:"n"},
    {i:92,u:1,s:2,r:"せいふく",w:"制服",v:"đồng phục",e:"uniform",p:"n"},
    {i:93,u:1,s:2,r:"せんざい",w:"洗剤",v:"chất tẩy rửa, nước rửa",e:"detergent",p:"n"},
    {i:94,u:1,s:2,r:"そこ",w:"底",v:"đáy",e:"bottom",p:"n"},
    {i:95,u:1,s:2,r:"ちか",w:"地下",v:"dưới lòng đất, tầng hầm",e:"underground, basement",p:"n"},
    {i:96,u:1,s:2,r:"てら",w:"寺",v:"chùa",e:"temple",p:"n"},
    {i:97,u:1,s:2,r:"どうろ",w:"道路",v:"đường, đường bộ",e:"road",p:"n"},
    {i:98,u:1,s:2,r:"さか",w:"坂",v:"dốc",e:"hill, slope",p:"n"},
    {i:99,u:1,s:2,r:"けむり",w:"煙",v:"khói",e:"smoke",p:"n"},
    {i:100,u:1,s:2,r:"はい",w:"灰",v:"tro",e:"ash",p:"n"},
    {i:101,u:1,s:2,r:"はん",w:"判",v:"con dấu",e:"seal, stamp",p:"n"},
    {i:102,u:1,s:2,r:"めいし",w:"名刺",v:"danh thiếp",e:"business card",p:"n"},
    {i:103,u:1,s:2,r:"めんきょ",w:"免許",v:"giấy phép, bằng (lái)",e:"license",p:"n"},
    {i:104,u:1,s:2,r:"おおく",w:"多く",v:"nhiều, phần nhiều, phần lớn",e:"many, much",p:"n"},
    {i:105,u:1,s:2,r:"ぜんはん",w:"前半",v:"nửa đầu, hiệp một",e:"first half",p:"n"},
    {i:106,u:1,s:2,r:"こうはん",w:"後半",v:"nửa sau, hiệp hai",e:"second half",p:"n"},
    {i:107,u:1,s:2,r:"さいこう",w:"最高",v:"cao nhất, tuyệt nhất",e:"highest, best",p:"n"},
    {i:108,u:1,s:2,r:"さいてい",w:"最低",v:"thấp nhất, tệ nhất",e:"lowest, worst",p:"n"},
    {i:109,u:1,s:2,r:"さいしょ",w:"最初",v:"đầu tiên, lúc đầu",e:"first, beginning",p:"n"},
    {i:110,u:1,s:2,r:"さいご",w:"最後",v:"cuối cùng, sau cùng",e:"last, end",p:"n"},
    {i:111,u:1,s:2,r:"じどう",w:"自動",v:"tự động",e:"automatic",p:"n"},
    {i:112,u:1,s:2,r:"しゅるい",w:"種類",v:"loại, chủng loại",e:"type, kind",p:"n"},
    {i:113,u:1,s:2,r:"せいかく",w:"性格",v:"tính cách",e:"personality, character",p:"n"},
    {i:114,u:1,s:2,r:"せいしつ",w:"性質",v:"tính chất, bản chất",e:"property, disposition",p:"n"},
    {i:115,u:1,s:2,r:"じゅんばん",w:"順番",v:"thứ tự, lượt",e:"order, sequence",p:"n"},
    {i:116,u:1,s:2,r:"ばん",w:"番",v:"lượt, phiên; sự trông coi",e:"one's turn; watch",p:"n"},
    {i:117,u:1,s:2,r:"ほうほう",w:"方法",v:"phương pháp, cách thức",e:"method, way",p:"n"},
    {i:118,u:1,s:2,r:"せいひん",w:"製品",v:"sản phẩm",e:"product",p:"n"},
    {i:119,u:1,s:2,r:"ねあがり",w:"値上がり",v:"sự tăng giá",e:"price rise",p:"v"},
    {i:120,u:1,s:2,r:"なま",w:"生",v:"sống, tươi (chưa nấu)",e:"raw, fresh",p:"n"},
    {i:121,u:2,s:1,r:"かわく",w:"渇く",v:"khát (nước)",e:"become thirsty",p:"v"},
    {i:122,u:2,s:1,r:"かぐ",w:"嗅ぐ",v:"ngửi",e:"smell",p:"v"},
    {i:123,u:2,s:1,r:"たたく",w:"叩く",v:"gõ, vỗ, đập",e:"tap, knock, clap",p:"v"},
    {i:124,u:2,s:1,r:"なぐる",w:"殴る",v:"đấm, đánh",e:"punch",p:"v"},
    {i:125,u:2,s:1,r:"ける",w:"蹴る",v:"đá",e:"kick",p:"v"},
    {i:126,u:2,s:1,r:"だく",w:"抱く",v:"ôm, bế",e:"hold, hug",p:"v"},
    {i:127,u:2,s:1,r:"たおれる",w:"倒れる",v:"đổ, ngã, gục",e:"fall over, collapse",p:"v"},
    {i:128,u:2,s:1,r:"たおす",w:"倒す",v:"làm đổ, đánh bại",e:"knock over, defeat",p:"v"},
    {i:129,u:2,s:1,r:"おこる",w:"起こる",v:"xảy ra, xảy đến; (起きる) thức dậy",e:"occur, happen",p:"v"},
    {i:130,u:2,s:1,r:"おこす",w:"起こす",v:"đánh thức; gây ra",e:"wake; cause",p:"v"},
    {i:131,u:2,s:1,r:"たずねる",w:"尋ねる",v:"hỏi",e:"ask",p:"v"},
    {i:132,u:2,s:1,r:"よぶ",w:"呼ぶ",v:"gọi, mời",e:"call",p:"v"},
    {i:133,u:2,s:1,r:"さけぶ",w:"叫ぶ",v:"hét, la lớn",e:"yell, shout",p:"v"},
    {i:134,u:2,s:1,r:"だまる",w:"黙る",v:"im lặng",e:"be silent",p:"v"},
    {i:135,u:2,s:1,r:"かう",w:"飼う",v:"nuôi (động vật)",e:"keep (a pet)",p:"v"},
    {i:136,u:2,s:1,r:"かぞえる",w:"数える",v:"đếm",e:"count",p:"v"},
    {i:137,u:2,s:1,r:"かわく",w:"乾く",v:"khô",e:"dry (intr.)",p:"v"},
    {i:138,u:2,s:1,r:"かわかす",w:"乾かす",v:"làm khô, hong khô",e:"dry (tr.)",p:"v"},
    {i:139,u:2,s:1,r:"たたむ",w:"畳む",v:"gấp, xếp gọn",e:"fold",p:"v"},
    {i:140,u:2,s:1,r:"さそう",w:"誘う",v:"rủ, mời",e:"invite",p:"v"},
    {i:141,u:2,s:1,r:"おこる",w:"怒る",v:"tức giận, nổi giận",e:"get angry",p:"v"},
    {i:142,u:2,s:1,r:"あずかる",w:"預かる",v:"giữ hộ, trông giữ",e:"look after, keep",p:"v"},
    {i:143,u:2,s:1,r:"あずける",w:"預ける",v:"gửi (đồ), nhờ giữ",e:"deposit, entrust",p:"v"},
    {i:144,u:2,s:1,r:"きまる",w:"決まる",v:"được quyết định",e:"be decided",p:"v"},
    {i:145,u:2,s:1,r:"きめる",w:"決める",v:"quyết định",e:"decide",p:"v"},
    {i:146,u:2,s:1,r:"うつる",w:"写る",v:"hiện lên/được chụp (vào ảnh)",e:"be photographed",p:"v"},
    {i:147,u:2,s:1,r:"うつす",w:"写す",v:"chụp (ảnh); sao chép",e:"copy, photograph",p:"v"},
    {i:148,u:2,s:1,r:"おもいだす",w:"思い出す",v:"nhớ ra, hồi tưởng",e:"recall",p:"v"},
    {i:149,u:2,s:1,r:"おそわる",w:"教わる",v:"được dạy, học (từ ai)",e:"be taught",p:"v"},
    {i:150,u:2,s:1,r:"もうしこむ",w:"申し込む",v:"đăng ký, đề nghị, xin",e:"apply",p:"v"},
    {i:151,u:2,s:1,r:"ことわる",w:"断る",v:"từ chối",e:"decline, refuse",p:"v"},
    {i:152,u:2,s:1,r:"みつかる",w:"見つかる",v:"được tìm thấy, bị phát hiện",e:"be found",p:"v"},
    {i:153,u:2,s:1,r:"みつける",w:"見つける",v:"tìm thấy, phát hiện",e:"find",p:"v"},
    {i:154,u:2,s:1,r:"つかまる",w:"捕まる",v:"bị bắt; bám/nắm vào",e:"be caught; hold on",p:"v"},
    {i:155,u:2,s:1,r:"つかまえる",w:"捕まえる",v:"bắt, tóm",e:"catch, arrest",p:"v"},
    {i:156,u:2,s:1,r:"のる",w:"乗る",v:"lên (xe), đi (xe)",e:"ride, get on",p:"v"},
    {i:157,u:2,s:1,r:"のせる",w:"乗せる",v:"cho lên xe, chở",e:"give a ride",p:"v"},
    {i:158,u:2,s:1,r:"おりる",w:"降りる",v:"xuống (xe), đi xuống",e:"get off, go down",p:"v"},
    {i:159,u:2,s:1,r:"おろす",w:"降ろす",v:"cho xuống; rút (tiền)",e:"take down; withdraw",p:"v"},
    {i:160,u:2,s:1,r:"なおる",w:"直る",v:"được sửa xong; cải thiện",e:"be fixed; improve",p:"v"},
    {i:161,u:2,s:1,r:"なおす",w:"直す",v:"sửa, chỉnh lại",e:"fix, correct",p:"v"},
    {i:162,u:2,s:1,r:"なおる",w:"治る",v:"khỏi (bệnh)",e:"get better, heal",p:"v"},
    {i:163,u:2,s:1,r:"なおす",w:"治す",v:"chữa khỏi",e:"cure",p:"v"},
    {i:164,u:2,s:1,r:"なくなる",w:"亡くなる",v:"qua đời, mất",e:"die",p:"v"},
    {i:165,u:2,s:1,r:"なくす",w:"亡くす",v:"mất (người thân)",e:"lose (someone)",p:"v"},
    {i:166,u:2,s:1,r:"うまれる",w:"生まれる",v:"được sinh ra, ra đời",e:"be born",p:"v"},
    {i:167,u:2,s:1,r:"うむ",w:"産む",v:"sinh, đẻ",e:"give birth",p:"v"},
    {i:168,u:2,s:1,r:"であう",w:"出会う",v:"gặp (tình cờ)",e:"meet by chance",p:"v"},
    {i:169,u:2,s:1,r:"たずねる",w:"訪ねる",v:"thăm, ghé thăm",e:"visit",p:"v"},
    {i:170,u:2,s:1,r:"つきあう",w:"付き合う",v:"giao thiệp; hẹn hò, qua lại",e:"associate with; date",p:"v"},
    {i:171,u:2,s:2,r:"きく",w:"効く",v:"có hiệu quả, có tác dụng (thuốc)",e:"be effective",p:"v"},
    {i:172,u:2,s:2,r:"はやる",w:"はやる",v:"thịnh hành; lan rộng (mốt, dịch)",e:"be popular, spread",p:"v"},
    {i:173,u:2,s:2,r:"たつ",w:"経つ",v:"(thời gian) trôi qua, trải qua",e:"elapse, pass (time)",p:"v"},
    {i:174,u:2,s:2,r:"まにあう",w:"間に合う",v:"kịp giờ; đủ dùng",e:"make it in time",p:"v"},
    {i:175,u:2,s:2,r:"まにあわせる",w:"間に合わせる",v:"làm cho kịp; tạm xoay xở",e:"finish in time; make do",p:"v"},
    {i:176,u:2,s:2,r:"つうじる",w:"通じる",v:"thông (đường, ý); hiểu được, truyền đạt",e:"go through; be understood",p:"v"},
    {i:177,u:2,s:2,r:"こむ",w:"込む",v:"đông đúc, chật",e:"be crowded",p:"v"},
    {i:178,u:2,s:2,r:"すれちがう",w:"すれ違う",v:"đi lướt qua nhau",e:"pass each other",p:"v"},
    {i:179,u:2,s:2,r:"かかる",w:"掛かる",v:"mất (thời gian/tiền); treo; mắc (bệnh); khởi động",e:"take; hang; be subjected to",p:"v"},
    {i:180,u:2,s:2,r:"かける",w:"掛ける",v:"treo; tốn; nhân; rưới; gọi (điện)",e:"hang; spend; multiply",p:"v"},
    {i:181,u:2,s:2,r:"うごく",w:"動く",v:"chuyển động, hoạt động",e:"move, work",p:"v"},
    {i:182,u:2,s:2,r:"うごかす",w:"動かす",v:"làm chuyển động, vận hành",e:"move, operate",p:"v"},
    {i:183,u:2,s:2,r:"はなれる",w:"離れる",v:"rời xa, tách ra",e:"be apart",p:"v"},
    {i:184,u:2,s:2,r:"はなす",w:"離す",v:"tách ra, để cách xa",e:"move apart, separate",p:"v"},
    {i:185,u:2,s:2,r:"ぶつける",w:"ぶつける",v:"va, đập, ném trúng",e:"hit, bang",p:"v"},
    {i:186,u:2,s:2,r:"ぶつかる",w:"ぶつかる",v:"va vào, đụng phải",e:"crash into",p:"v"},
    {i:187,u:2,s:2,r:"こぼれる",w:"こぼれる",v:"tràn ra, đổ ra",e:"spill, overflow",p:"v"},
    {i:188,u:2,s:2,r:"こぼす",w:"こぼす",v:"làm đổ, làm tràn",e:"spill",p:"v"},
    {i:189,u:2,s:2,r:"ふく",w:"拭く",v:"lau, chùi",e:"wipe",p:"v"},
    {i:190,u:2,s:2,r:"かたづく",w:"片付く",v:"được dọn dẹp, xong xuôi",e:"be tidied, settled",p:"v"},
    {i:191,u:2,s:2,r:"かたづける",w:"片付ける",v:"dọn dẹp, sắp xếp",e:"tidy, finish",p:"v"},
    {i:192,u:2,s:2,r:"つつむ",w:"包む",v:"gói, bọc",e:"wrap",p:"v"},
    {i:193,u:2,s:2,r:"はる",w:"張る",v:"dán, căng",e:"put up, affix",p:"v"},
    {i:194,u:2,s:2,r:"なくなる",w:"無くなる",v:"hết, mất đi, biến mất",e:"be lost, run out",p:"v"},
    {i:195,u:2,s:2,r:"なくす",w:"無くす",v:"làm mất",e:"lose",p:"v"},
    {i:196,u:2,s:2,r:"たりる",w:"足りる",v:"đủ",e:"be sufficient",p:"v"},
    {i:197,u:2,s:2,r:"のこる",w:"残る",v:"còn lại, sót lại",e:"remain",p:"v"},
    {i:198,u:2,s:2,r:"のこす",w:"残す",v:"để lại, chừa lại",e:"leave behind",p:"v"},
    {i:199,u:2,s:2,r:"くさる",w:"腐る",v:"thối, hỏng (đồ ăn)",e:"rot",p:"v"},
    {i:200,u:2,s:2,r:"むける",w:"剝ける",v:"bị bong, tróc (da/vỏ)",e:"peel off",p:"v"},
    {i:201,u:2,s:2,r:"むく",w:"剝く",v:"gọt, bóc (vỏ)",e:"peel",p:"v"},
    {i:202,u:2,s:2,r:"すべる",w:"滑る",v:"trượt",e:"skate, slip",p:"v"},
    {i:203,u:2,s:2,r:"つもる",w:"積もる",v:"chất đống; (tuyết/bụi) đọng lại",e:"accumulate, pile up",p:"v"},
    {i:204,u:2,s:2,r:"つむ",w:"積む",v:"chất, xếp lên; tích lũy",e:"pile, load",p:"v"},
    {i:205,u:2,s:2,r:"あく",w:"空く",v:"trống ra; rảnh; thủng",e:"be vacant; be free",p:"v"},
    {i:206,u:2,s:2,r:"あける",w:"空ける",v:"làm trống, để trống; khoét",e:"vacate; make (a hole)",p:"v"},
    {i:207,u:2,s:2,r:"さがる",w:"下がる",v:"giảm, tụt xuống; lùi lại",e:"go down; step back",p:"v"},
    {i:208,u:2,s:2,r:"さげる",w:"下げる",v:"hạ xuống, làm giảm; dọn đi",e:"lower; take away",p:"v"},
    {i:209,u:2,s:2,r:"ひえる",w:"冷える",v:"lạnh đi, nguội; ớn lạnh",e:"be chilled",p:"v"},
    {i:210,u:2,s:2,r:"ひやす",w:"冷やす",v:"làm lạnh, ướp lạnh",e:"chill",p:"v"},
    {i:211,u:2,s:2,r:"さめる",w:"冷める",v:"nguội đi; (nhiệt huyết) nguội",e:"get cold",p:"v"},
    {i:212,u:2,s:2,r:"さます",w:"冷ます",v:"làm nguội",e:"cool down",p:"v"},
    {i:213,u:2,s:2,r:"ふえる",w:"増える",v:"tăng lên",e:"increase",p:"v"},
    {i:214,u:2,s:2,r:"ふやす",w:"増やす",v:"làm tăng, tăng thêm",e:"increase (tr.)",p:"v"},
    {i:215,u:2,s:2,r:"わく",w:"沸く",v:"sôi",e:"boil (intr.)",p:"v"},
    {i:216,u:2,s:2,r:"わかす",w:"沸かす",v:"đun sôi",e:"boil (tr.)",p:"v"},
    {i:217,u:2,s:2,r:"なる",w:"鳴る",v:"kêu, reo, vang (chuông)",e:"ring, sound",p:"v"},
    {i:218,u:2,s:2,r:"ならす",w:"鳴らす",v:"làm kêu, rung (chuông)",e:"sound (tr.)",p:"v"},
    {i:219,u:2,s:2,r:"やくだつ",w:"役立つ",v:"có ích, hữu ích",e:"be helpful",p:"v"},
    {i:220,u:2,s:2,r:"やくだてる",w:"役立てる",v:"tận dụng, dùng vào việc có ích",e:"put to use",p:"v"},
    {i:221,u:2,s:3,r:"かざり",w:"飾り",v:"đồ trang trí, sự trang trí",e:"decoration",p:"n"},
    {i:222,u:2,s:3,r:"あそび",w:"遊び",v:"trò chơi, sự vui chơi",e:"game, play",p:"n"},
    {i:223,u:2,s:3,r:"あつまり",w:"集まり",v:"cuộc tụ họp, buổi gặp mặt",e:"gathering",p:"n"},
    {i:224,u:2,s:3,r:"おしえ",w:"教え",v:"lời dạy, sự chỉ dạy",e:"teachings",p:"n"},
    {i:225,u:2,s:3,r:"おどり",w:"踊り",v:"điệu múa, vũ điệu",e:"dance",p:"n"},
    {i:226,u:2,s:3,r:"おもい",w:"思い",v:"suy nghĩ, tình cảm, tâm tư",e:"thoughts, feelings",p:"n"},
    {i:227,u:2,s:3,r:"かんがえ",w:"考え",v:"ý nghĩ, ý kiến, suy nghĩ",e:"thought, idea",p:"n"},
    {i:228,u:2,s:3,r:"かたづけ",w:"片づけ",v:"việc dọn dẹp",e:"tidying",p:"n"},
    {i:229,u:2,s:3,r:"てつだい",w:"手伝い",v:"sự giúp đỡ; người giúp việc",e:"help",p:"n"},
    {i:230,u:2,s:3,r:"はたらき",w:"働き",v:"chức năng; sự hoạt động; công lao",e:"function, action",p:"n"},
    {i:231,u:2,s:3,r:"きまり",w:"決まり",v:"quy định, quy tắc",e:"rule",p:"n"},
    {i:232,u:2,s:3,r:"さわぎ",w:"騒ぎ",v:"sự ồn ào, náo loạn",e:"commotion, trouble",p:"n"},
    {i:233,u:2,s:3,r:"しらせ",w:"知らせ",v:"thông báo, tin báo",e:"notification, news",p:"n"},
    {i:234,u:2,s:3,r:"たのみ",w:"頼み",v:"lời nhờ vả, thỉnh cầu",e:"request",p:"n"},
    {i:235,u:2,s:3,r:"つかれ",w:"疲れ",v:"sự mệt mỏi",e:"fatigue",p:"n"},
    {i:236,u:2,s:3,r:"ちがい",w:"違い",v:"sự khác nhau, điểm khác biệt",e:"difference",p:"n"},
    {i:237,u:2,s:3,r:"はじめ",w:"始め",v:"sự bắt đầu, lúc đầu",e:"beginning",p:"n"},
    {i:238,u:2,s:3,r:"つづき",w:"続き",v:"phần tiếp theo, phần còn lại",e:"continuation",p:"n"},
    {i:239,u:2,s:3,r:"くれ",w:"暮れ",v:"cuối năm; hoàng hôn, chạng vạng",e:"end of the year; dusk",p:"n"},
    {i:240,u:2,s:3,r:"いき",w:"行き",v:"lượt đi, chuyến đi",e:"going (trip out)",p:"n"},
    {i:241,u:2,s:3,r:"かえり",w:"帰り",v:"lượt về, lúc về",e:"returning",p:"n"},
    {i:242,u:2,s:3,r:"いそぎ",w:"急ぎ",v:"sự vội, việc gấp",e:"urgency",p:"n"},
    {i:243,u:2,s:3,r:"おくれ",w:"遅れ",v:"sự chậm trễ, sự trễ",e:"delay",p:"n"},
    {i:244,u:2,s:3,r:"かし",w:"貸し",v:"sự cho vay, khoản cho vay; ơn",e:"loan, lending",p:"n"},
    {i:245,u:2,s:3,r:"かり",w:"借り",v:"sự vay, khoản nợ",e:"debt, borrowing",p:"n"},
    {i:246,u:2,s:3,r:"かち",w:"勝ち",v:"chiến thắng",e:"victory",p:"n"},
    {i:247,u:2,s:3,r:"まけ",w:"負け",v:"sự thua, thất bại",e:"defeat",p:"n"},
    {i:248,u:2,s:3,r:"むかえ",w:"迎え",v:"sự/người đi đón",e:"picking up",p:"n"},
    {i:249,u:2,s:3,r:"はじまり",w:"始まり",v:"sự khởi đầu, sự bắt đầu",e:"beginning",p:"n"},
    {i:250,u:2,s:3,r:"おわり",w:"終わり",v:"sự kết thúc, kết cục",e:"end",p:"n"},
    {i:251,u:2,s:3,r:"もどり",w:"戻り",v:"sự quay về",e:"return",p:"n"},
    {i:252,u:2,s:3,r:"わかれ",w:"別れ",v:"sự chia tay, ly biệt",e:"parting",p:"n"},
    {i:253,u:2,s:3,r:"よろこび",w:"喜び",v:"niềm vui, niềm hân hoan",e:"joy",p:"n"},
    {i:254,u:2,s:3,r:"たのしみ",w:"楽しみ",v:"niềm vui; sự mong đợi, háo hức",e:"fun; pleasure",p:"n"},
    {i:255,u:2,s:3,r:"わらい",w:"笑い",v:"tiếng cười, nụ cười",e:"laughter",p:"n"},
    {i:256,u:2,s:3,r:"おどろき",w:"驚き",v:"sự ngạc nhiên",e:"surprise",p:"n"},
    {i:257,u:2,s:3,r:"いかり",w:"怒り",v:"sự tức giận, cơn giận",e:"anger",p:"n"},
    {i:258,u:2,s:3,r:"かなしみ",w:"悲しみ",v:"nỗi buồn, sự đau buồn",e:"sadness",p:"n"},
    {i:259,u:3,s:1,r:"しあわせな",w:"幸せな",v:"hạnh phúc",e:"happy",p:"a"},
    {i:260,u:3,s:1,r:"とくいな",w:"得意な",v:"giỏi, sở trường; tự tin/tự đắc",e:"strong at; proud",p:"a"},
    {i:261,u:3,s:1,r:"にがてな",w:"苦手な",v:"kém, không giỏi; ngại, ngán",e:"weak at; not good at",p:"a"},
    {i:262,u:3,s:1,r:"ねっしんな",w:"熱心な",v:"nhiệt tình, hăng say",e:"enthusiastic",p:"a"},
    {i:263,u:3,s:1,r:"むちゅうな",w:"夢中な",v:"mê mải, say sưa",e:"absorbed, crazy about",p:"a"},
    {i:264,u:3,s:1,r:"たいくつな",w:"退屈な",v:"chán, buồn tẻ",e:"boring",p:"a"},
    {i:265,u:3,s:1,r:"けんこうな",w:"健康な",v:"khỏe mạnh",e:"healthy",p:"a"},
    {i:266,u:3,s:1,r:"くるしい",w:"苦しい",v:"đau khổ, vất vả, ngột ngạt",e:"agonizing, rough",p:"a"},
    {i:267,u:3,s:1,r:"へいきな",w:"平気な",v:"bình thản, không sao",e:"unfazed, calm",p:"a"},
    {i:268,u:3,s:1,r:"くやしい",w:"悔しい",v:"cay cú, tiếc nuối, ấm ức",e:"frustrating",p:"a"},
    {i:269,u:3,s:1,r:"うらやましい",w:"うらやましい",v:"ghen tị, thèm muốn",e:"envious",p:"a"},
    {i:270,u:3,s:1,r:"かゆい",w:"かゆい",v:"ngứa",e:"itchy",p:"a"},
    {i:271,u:3,s:1,r:"おとなしい",w:"おとなしい",v:"hiền lành, ngoan, trầm tính",e:"quiet, subdued",p:"a"},
    {i:272,u:3,s:1,r:"がまんづよい",w:"我慢強い",v:"kiên nhẫn, bền bỉ",e:"perseverant",p:"a"},
    {i:273,u:3,s:1,r:"しょうじきな",w:"正直な",v:"thật thà, trung thực",e:"honest",p:"a"},
    {i:274,u:3,s:1,r:"けちな",w:"けちな",v:"keo kiệt, bủn xỉn",e:"stingy",p:"a"},
    {i:275,u:3,s:1,r:"わがままな",w:"わがままな",v:"ích kỷ, tùy tiện, bướng bỉnh",e:"selfish",p:"a"},
    {i:276,u:3,s:1,r:"せっきょくてきな",w:"積極的な",v:"tích cực, chủ động",e:"active, positive",p:"a"},
    {i:277,u:3,s:1,r:"しょうきょくてきな",w:"消極的な",v:"tiêu cực, thụ động",e:"passive, negative",p:"a"},
    {i:278,u:3,s:1,r:"まんぞくな",w:"満足な",v:"thỏa mãn, hài lòng, đầy đủ",e:"satisfying",p:"a"},
    {i:279,u:3,s:1,r:"ふまんな",w:"不満な",v:"bất mãn, không hài lòng",e:"dissatisfied",p:"a"},
    {i:280,u:3,s:1,r:"ふあんな",w:"不安な",v:"bất an, lo lắng",e:"uneasy, worrisome",p:"a"},
    {i:281,u:3,s:1,r:"たいへんな",w:"大変な",v:"vất vả; khủng khiếp, ghê gớm",e:"tough, awful",p:"a"},
    {i:282,u:3,s:1,r:"むりな",w:"無理な",v:"vô lý; không thể; gắng quá sức",e:"impossible, unreasonable",p:"a"},
    {i:283,u:3,s:1,r:"ふちゅういな",w:"不注意な",v:"bất cẩn, thiếu chú ý",e:"careless",p:"a"},
    {i:284,u:3,s:1,r:"らくな",w:"楽な",v:"thoải mái, dễ chịu, nhàn",e:"easy, comfortable",p:"a"},
    {i:285,u:3,s:1,r:"めんどうな",w:"面倒な",v:"phiền phức, rắc rối",e:"troublesome",p:"a"},
    {i:286,u:3,s:1,r:"しつれいな",w:"失礼な",v:"thất lễ, bất lịch sự",e:"rude",p:"a"},
    {i:287,u:3,s:1,r:"とうぜんな",w:"当然な",v:"đương nhiên, hiển nhiên",e:"natural, expected",p:"a"},
    {i:288,u:3,s:1,r:"いがいな",w:"意外な",v:"bất ngờ, ngoài dự đoán",e:"unexpected",p:"a"},
    {i:289,u:3,s:1,r:"けっこうな",w:"結構な",v:"tốt, ổn; thôi đủ rồi (từ chối)",e:"nice, fine; no thanks",p:"a"},
    {i:290,u:3,s:1,r:"はでな",w:"派手な",v:"sặc sỡ, lòe loẹt, phô trương",e:"flashy, fancy",p:"a"},
    {i:291,u:3,s:1,r:"じみな",w:"地味な",v:"giản dị, trầm, nhã nhặn",e:"plain",p:"a"},
    {i:292,u:3,s:1,r:"おしゃれな",w:"おしゃれな",v:"sành điệu, thời trang, bảnh",e:"stylish",p:"a"},
    {i:293,u:3,s:1,r:"へんな",w:"変な",v:"kỳ lạ, lạ",e:"strange",p:"a"},
    {i:294,u:3,s:1,r:"ふしぎな",w:"不思議な",v:"kỳ diệu, khó hiểu, bí ẩn",e:"mysterious",p:"a"},
    {i:295,u:3,s:1,r:"ましな",w:"ましな",v:"khá hơn, đỡ hơn, tạm ổn",e:"preferable, better",p:"a"},
    {i:296,u:3,s:1,r:"むだな",w:"無駄な",v:"lãng phí, vô ích",e:"futile, wasteful",p:"a"},
    {i:297,u:3,s:1,r:"じゆうな",w:"自由な",v:"tự do",e:"free",p:"a"},
    {i:298,u:3,s:1,r:"ふじゆうな",w:"不自由な",v:"bất tiện; khiếm khuyết (cơ thể); thiếu thốn",e:"inconvenient; disabled",p:"a"},
    {i:299,u:3,s:2,r:"あたたまる",w:"温まる",v:"ấm lên",e:"become warm",p:"v"},
    {i:300,u:3,s:2,r:"あたためる",w:"温める",v:"làm ấm, hâm nóng",e:"warm, heat",p:"v"},
    {i:301,u:3,s:2,r:"たかまる",w:"高まる",v:"tăng cao, dâng cao",e:"rise, heighten",p:"v"},
    {i:302,u:3,s:2,r:"たかめる",w:"高める",v:"nâng cao",e:"raise, heighten",p:"v"},
    {i:303,u:3,s:2,r:"つよまる",w:"強まる",v:"mạnh lên",e:"strengthen (intr.)",p:"v"},
    {i:304,u:3,s:2,r:"つよめる",w:"強める",v:"làm mạnh thêm, tăng cường",e:"strengthen (tr.)",p:"v"},
    {i:305,u:3,s:2,r:"よわまる",w:"弱まる",v:"yếu đi",e:"weaken (intr.)",p:"v"},
    {i:306,u:3,s:2,r:"よわめる",w:"弱める",v:"làm yếu đi, giảm",e:"weaken (tr.)",p:"v"},
    {i:307,u:3,s:2,r:"ひろまる",w:"広まる",v:"lan rộng, được truyền bá",e:"spread (intr.)",p:"v"},
    {i:308,u:3,s:2,r:"ひろめる",w:"広める",v:"truyền bá, phổ biến",e:"spread, popularize",p:"v"},
    {i:309,u:3,s:2,r:"ふかまる",w:"深まる",v:"sâu sắc thêm",e:"deepen (intr.)",p:"v"},
    {i:310,u:3,s:2,r:"ふかめる",w:"深める",v:"làm sâu sắc thêm",e:"deepen (tr.)",p:"v"},
    {i:311,u:4,s:1,r:"せわ",w:"世話",v:"sự chăm sóc, giúp đỡ",e:"care, support",p:"n"},
    {i:312,u:4,s:1,r:"かてい",w:"家庭",v:"gia đình, gia cảnh",e:"home, household",p:"n"},
    {i:313,u:4,s:1,r:"きょうりょく",w:"協力",v:"hợp tác, hợp lực",e:"cooperation",p:"n"},
    {i:314,u:4,s:1,r:"かんしゃ",w:"感謝",v:"sự cảm tạ, lòng biết ơn",e:"gratitude, thanks",p:"n"},
    {i:315,u:4,s:1,r:"おれい",w:"お礼",v:"lời/quà cảm ơn, sự đáp lễ",e:"thanks, token of gratitude",p:"n"},
    {i:316,u:4,s:1,r:"おわび",w:"お詫び",v:"lời xin lỗi",e:"apology",p:"n"},
    {i:317,u:4,s:1,r:"おじぎ",w:"おじぎ",v:"sự cúi chào",e:"bow",p:"n"},
    {i:318,u:4,s:1,r:"あくしゅ",w:"握手",v:"bắt tay",e:"handshake",p:"n"},
    {i:319,u:4,s:1,r:"いじわる",w:"意地悪",v:"ác ý, xấu bụng, chơi xấu",e:"spite",p:"n"},
    {i:320,u:4,s:1,r:"いたずら",w:"いたずら",v:"trò nghịch, sự nghịch ngợm",e:"prank, mischief",p:"n"},
    {i:321,u:4,s:1,r:"せつやく",w:"節約",v:"tiết kiệm",e:"saving (money/electricity)",p:"n"},
    {i:322,u:4,s:1,r:"けいえい",w:"経営",v:"kinh doanh, quản lý (doanh nghiệp)",e:"management",p:"n"},
    {i:323,u:4,s:1,r:"はんせい",w:"反省",v:"tự kiểm điểm, suy xét lại",e:"reflection, remorse",p:"n"},
    {i:324,u:4,s:1,r:"じっこう",w:"実行",v:"thực hiện, thi hành",e:"implementation",p:"n"},
    {i:325,u:4,s:1,r:"しんぽ",w:"進歩",v:"tiến bộ",e:"progress",p:"n"},
    {i:326,u:4,s:1,r:"へんか",w:"変化",v:"thay đổi, biến đổi",e:"change",p:"n"},
    {i:327,u:4,s:1,r:"はったつ",w:"発達",v:"phát triển, phát đạt",e:"development",p:"n"},
    {i:328,u:4,s:1,r:"たいりょく",w:"体力",v:"thể lực, sức khỏe",e:"physical strength",p:"n"},
    {i:329,u:4,s:1,r:"しゅつじょう",w:"出場",v:"tham gia (thi đấu), ra sân",e:"participation",p:"n"},
    {i:330,u:4,s:1,r:"かつやく",w:"活躍",v:"hoạt động tích cực, tỏa sáng",e:"activity",p:"n"},
    {i:331,u:4,s:1,r:"きょうそう",w:"競争",v:"cạnh tranh, ganh đua",e:"competition",p:"n"},
    {i:332,u:4,s:1,r:"おうえん",w:"応援",v:"cổ vũ, ủng hộ",e:"cheering, support",p:"n"},
    {i:333,u:4,s:1,r:"はくしゅ",w:"拍手",v:"vỗ tay",e:"applause",p:"n"},
    {i:334,u:4,s:1,r:"にんき",w:"人気",v:"sự nổi tiếng, được ưa thích",e:"popularity",p:"n"},
    {i:335,u:4,s:1,r:"うわさ",w:"うわさ",v:"lời đồn, tin đồn",e:"rumor",p:"n"},
    {i:336,u:4,s:1,r:"じょうほう",w:"情報",v:"thông tin",e:"information",p:"n"},
    {i:337,u:4,s:1,r:"こうかん",w:"交換",v:"trao đổi, thay thế",e:"exchange",p:"n"},
    {i:338,u:4,s:1,r:"りゅうこう",w:"流行",v:"thịnh hành; lưu hành (dịch)",e:"fashion; spread",p:"n"},
    {i:339,u:4,s:1,r:"せんでん",w:"宣伝",v:"tuyên truyền, quảng cáo",e:"publicity",p:"n"},
    {i:340,u:4,s:1,r:"こうこく",w:"広告",v:"quảng cáo, mẩu quảng cáo",e:"advertisement",p:"n"},
    {i:341,u:4,s:1,r:"ちゅうもく",w:"注目",v:"sự chú ý, chú mục",e:"attention",p:"n"},
    {i:342,u:4,s:1,r:"つうやく",w:"通訳",v:"phiên dịch (nói), thông dịch",e:"interpretation",p:"n"},
    {i:343,u:4,s:1,r:"ほんやく",w:"翻訳",v:"dịch (viết), biên dịch",e:"translation",p:"n"},
    {i:344,u:4,s:1,r:"でんごん",w:"伝言",v:"lời nhắn",e:"message",p:"n"},
    {i:345,u:4,s:1,r:"ほうこく",w:"報告",v:"báo cáo",e:"report",p:"n"},
    {i:346,u:4,s:1,r:"ろくが",w:"録画",v:"ghi hình, thu hình",e:"video recording",p:"n"},
    {i:347,u:4,s:1,r:"こんざつ",w:"混雑",v:"sự đông đúc, chen chúc",e:"crowd",p:"n"},
    {i:348,u:4,s:1,r:"じゅうたい",w:"渋滞",v:"tắc nghẽn, kẹt xe",e:"congestion",p:"n"},
    {i:349,u:4,s:1,r:"しょうとつ",w:"衝突",v:"va chạm, xung đột",e:"collision, conflict",p:"n"},
    {i:350,u:4,s:1,r:"ひがい",w:"被害",v:"thiệt hại",e:"damage",p:"n"},
    {i:351,u:4,s:1,r:"じこ",w:"事故",v:"tai nạn",e:"accident",p:"n"},
    {i:352,u:4,s:1,r:"じけん",w:"事件",v:"vụ việc, sự kiện (xấu)",e:"incident, event",p:"n"},
    {i:353,u:4,s:1,r:"こしょう",w:"故障",v:"hỏng hóc, trục trặc",e:"malfunction, breakdown",p:"n"},
    {i:354,u:4,s:1,r:"しゅうり",w:"修理",v:"sửa chữa",e:"repair",p:"n"},
    {i:355,u:4,s:1,r:"ていでん",w:"停電",v:"mất điện, cúp điện",e:"blackout",p:"n"},
    {i:356,u:4,s:1,r:"ちょうし",w:"調子",v:"tình trạng, phong độ; nhịp điệu",e:"condition, tone",p:"n"},
    {i:357,u:4,s:1,r:"きんちょう",w:"緊張",v:"căng thẳng, hồi hộp",e:"tension",p:"n"},
    {i:358,u:4,s:1,r:"じしん",w:"自信",v:"sự tự tin",e:"confidence",p:"n"},
    {i:359,u:4,s:1,r:"じまん",w:"自慢",v:"tự hào, khoe khoang",e:"pride, boast",p:"n"},
    {i:360,u:4,s:1,r:"かんしん",w:"感心",v:"khâm phục; đáng khen",e:"admiration",p:"n"},
    {i:361,u:4,s:1,r:"かんどう",w:"感動",v:"cảm động, xúc động",e:"being moved",p:"n"},
    {i:362,u:4,s:1,r:"こうふん",w:"興奮",v:"hưng phấn, kích động",e:"excitement",p:"n"},
    {i:363,u:4,s:1,r:"かんそう",w:"感想",v:"cảm tưởng, cảm nghĩ",e:"impression",p:"n"},
    {i:364,u:4,s:1,r:"よそう",w:"予想",v:"dự đoán, dự kiến",e:"forecast",p:"n"},
    {i:365,u:4,s:1,r:"せんもん",w:"専門",v:"chuyên môn, chuyên ngành",e:"specialty",p:"n"},
    {i:366,u:4,s:1,r:"けんきゅう",w:"研究",v:"nghiên cứu",e:"research",p:"n"},
    {i:367,u:4,s:1,r:"ちょうさ",w:"調査",v:"điều tra, khảo sát",e:"survey",p:"n"},
    {i:368,u:4,s:1,r:"げんいん",w:"原因",v:"nguyên nhân",e:"cause",p:"n"},
    {i:369,u:4,s:1,r:"けっか",w:"結果",v:"kết quả",e:"result",p:"n"},
    {i:370,u:4,s:1,r:"かいけつ",w:"解決",v:"giải quyết",e:"solution",p:"n"},
    {i:371,u:4,s:2,r:"かくにん",w:"確認",v:"xác nhận",e:"confirmation",p:"n"},
    {i:372,u:4,s:2,r:"りよう",w:"利用",v:"sử dụng, lợi dụng, tận dụng",e:"use, exploitation",p:"n"},
    {i:373,u:4,s:2,r:"りかい",w:"理解",v:"hiểu, lý giải",e:"understanding",p:"n"},
    {i:374,u:4,s:2,r:"はっけん",w:"発見",v:"phát hiện",e:"discovery",p:"n"},
    {i:375,u:4,s:2,r:"はつめい",w:"発明",v:"phát minh",e:"invention",p:"n"},
    {i:376,u:4,s:2,r:"かんけい",w:"関係",v:"quan hệ, liên quan",e:"relationship",p:"n"},
    {i:377,u:4,s:2,r:"だんたい",w:"団体",v:"đoàn thể, tập thể",e:"group",p:"n"},
    {i:378,u:4,s:2,r:"せんきょ",w:"選挙",v:"bầu cử",e:"election",p:"n"},
    {i:379,u:4,s:2,r:"ぜいきん",w:"税金",v:"tiền thuế",e:"tax",p:"n"},
    {i:380,u:4,s:2,r:"せきにん",w:"責任",v:"trách nhiệm",e:"responsibility",p:"n"},
    {i:381,u:4,s:2,r:"しょるい",w:"書類",v:"giấy tờ, tài liệu",e:"document",p:"n"},
    {i:382,u:4,s:2,r:"だいめい",w:"題名",v:"tựa đề, tên (tác phẩm)",e:"title",p:"n"},
    {i:383,u:4,s:2,r:"じょうけん",w:"条件",v:"điều kiện",e:"condition",p:"n"},
    {i:384,u:4,s:2,r:"しめきり",w:"締め切り",v:"hạn chót, kỳ hạn cuối",e:"deadline",p:"n"},
    {i:385,u:4,s:2,r:"きかん",w:"期間",v:"kỳ hạn, khoảng thời gian",e:"period",p:"n"},
    {i:386,u:4,s:2,r:"ばい",w:"倍",v:"gấp đôi; ~ lần",e:"double; ~ times",p:"n"},
    {i:387,u:4,s:2,r:"くじ",w:"くじ",v:"thẻ xổ số, việc rút thăm",e:"lot, lottery",p:"n"},
    {i:388,u:4,s:2,r:"ちかみち",w:"近道",v:"đường tắt",e:"shortcut",p:"n"},
    {i:389,u:4,s:2,r:"ちゅうしん",w:"中心",v:"trung tâm, trọng tâm",e:"center",p:"n"},
    {i:390,u:4,s:2,r:"あたり",w:"辺り",v:"xung quanh, lân cận; khoảng",e:"surroundings, around",p:"n"},
    {i:391,u:4,s:2,r:"まわり",w:"周り",v:"xung quanh, chu vi",e:"around, circumference",p:"n"},
    {i:392,u:4,s:2,r:"あな",w:"穴",v:"lỗ, hố",e:"hole",p:"n"},
    {i:393,u:4,s:2,r:"れつ",w:"列",v:"hàng, dãy",e:"line, row",p:"n"},
    {i:394,u:4,s:2,r:"はば",w:"幅",v:"chiều rộng, bề ngang; phạm vi",e:"width, range",p:"n"},
    {i:395,u:4,s:2,r:"はんい",w:"範囲",v:"phạm vi",e:"scope, extent",p:"n"},
    {i:396,u:4,s:2,r:"ないよう",w:"内容",v:"nội dung",e:"content",p:"n"},
    {i:397,u:4,s:2,r:"なかみ",w:"中身",v:"bên trong, ruột, nội dung thực",e:"contents, gist",p:"n"},
    {i:398,u:4,s:2,r:"とくちょう",w:"特徴",v:"đặc trưng, đặc điểm",e:"feature",p:"n"},
    {i:399,u:4,s:2,r:"ふつう",w:"普通",v:"thông thường, bình thường",e:"ordinary, normal",p:"n"},
    {i:400,u:4,s:2,r:"あたりまえ",w:"当たり前",v:"đương nhiên, hiển nhiên",e:"natural, obvious",p:"n"},
    {i:401,u:4,s:2,r:"にせ",w:"偽",v:"giả, đồ giả",e:"fake",p:"n"},
    {i:402,u:4,s:2,r:"べつ",w:"別",v:"khác, riêng",e:"difference, separate",p:"n"},
    {i:403,u:4,s:2,r:"こくせき",w:"国籍",v:"quốc tịch",e:"nationality",p:"n"},
    {i:404,u:4,s:2,r:"とうよう",w:"東洋",v:"phương Đông",e:"the Orient",p:"n"},
    {i:405,u:4,s:2,r:"せいよう",w:"西洋",v:"phương Tây",e:"the West",p:"n"},
    {i:406,u:4,s:2,r:"こくさい",w:"国際",v:"quốc tế",e:"international",p:"n"},
    {i:407,u:4,s:2,r:"しぜん",w:"自然",v:"tự nhiên, thiên nhiên",e:"nature",p:"n"},
    {i:408,u:4,s:2,r:"けしき",w:"景色",v:"phong cảnh, cảnh sắc",e:"scenery",p:"n"},
    {i:409,u:4,s:2,r:"しゅうきょう",w:"宗教",v:"tôn giáo",e:"religion",p:"n"},
    {i:410,u:4,s:2,r:"あい",w:"愛",v:"tình yêu, yêu",e:"love",p:"n"},
    {i:411,u:5,s:1,r:"とどく",w:"届く",v:"đến nơi, với tới",e:"be delivered, reach",p:"v"},
    {i:412,u:5,s:1,r:"とどける",w:"届ける",v:"giao, gửi tới; trình báo",e:"deliver, notify",p:"v"},
    {i:413,u:5,s:1,r:"かく",w:"かく",v:"gãi; đổ (mồ hôi); chuốc (nhục)",e:"scratch; emit (sweat)",p:"v"},
    {i:414,u:5,s:1,r:"つかむ",w:"つかむ",v:"nắm, chộp; giành được",e:"grab, grasp; acquire",p:"v"},
    {i:415,u:5,s:1,r:"にぎる",w:"握る",v:"nắm chặt; nắm (cơm)",e:"grip, squeeze",p:"v"},
    {i:416,u:5,s:1,r:"おさえる",w:"押さえる",v:"giữ, ấn, đè",e:"hold down, press",p:"v"},
    {i:417,u:5,s:1,r:"ちかづく",w:"近づく",v:"đến gần, tiếp cận",e:"approach",p:"v"},
    {i:418,u:5,s:1,r:"ちかづける",w:"近づける",v:"làm cho gần lại, để gần",e:"bring near",p:"v"},
    {i:419,u:5,s:1,r:"あう",w:"合う",v:"hợp, khớp, đúng",e:"match, fit",p:"v"},
    {i:420,u:5,s:1,r:"あわせる",w:"合わせる",v:"ghép, kết hợp; chỉnh cho khớp",e:"combine; match",p:"v"},
    {i:421,u:5,s:1,r:"あたる",w:"当たる",v:"trúng, đúng; trúng (thưởng)",e:"hit; be right; win",p:"v"},
    {i:422,u:5,s:1,r:"あてる",w:"当てる",v:"làm trúng; đoán trúng; áp vào",e:"hit; guess",p:"v"},
    {i:423,u:5,s:1,r:"くらべる",w:"比べる",v:"so sánh",e:"compare",p:"v"},
    {i:424,u:5,s:1,r:"にあう",w:"似合う",v:"hợp (với), trông xứng",e:"look good on",p:"v"},
    {i:425,u:5,s:1,r:"にせる",w:"似せる",v:"làm cho giống, mô phỏng",e:"imitate",p:"v"},
    {i:426,u:5,s:1,r:"にる",w:"似る",v:"giống",e:"resemble",p:"v"},
    {i:427,u:5,s:1,r:"わかれる",w:"分かれる",v:"được phân chia, tách ra",e:"be divided",p:"v"},
    {i:428,u:5,s:1,r:"わける",w:"分ける",v:"chia, phân chia",e:"divide, share",p:"v"},
    {i:429,u:5,s:1,r:"たす",w:"足す",v:"thêm, cộng",e:"add",p:"v"},
    {i:430,u:5,s:1,r:"ひく",w:"引く",v:"kéo; trừ; tra (từ điển)",e:"pull; subtract; look up",p:"v"},
    {i:431,u:5,s:1,r:"ふえる",w:"増える",v:"tăng lên",e:"increase (intr.)",p:"v"},
    {i:432,u:5,s:1,r:"ふやす",w:"増やす",v:"làm tăng",e:"increase (tr.)",p:"v"},
    {i:433,u:5,s:1,r:"へる",w:"減る",v:"giảm",e:"decrease (intr.)",p:"v"},
    {i:434,u:5,s:1,r:"へらす",w:"減らす",v:"làm giảm",e:"decrease (tr.)",p:"v"},
    {i:435,u:5,s:1,r:"かわる",w:"変わる",v:"thay đổi, biến đổi",e:"change (intr.)",p:"v"},
    {i:436,u:5,s:1,r:"かえる",w:"変える",v:"làm thay đổi, đổi",e:"change (tr.)",p:"v"},
    {i:437,u:5,s:1,r:"かわる",w:"替わる",v:"thay thế (vị trí, ca)",e:"be substituted",p:"v"},
    {i:438,u:5,s:1,r:"かえる",w:"替える",v:"thay, đổi (cái này lấy cái kia)",e:"replace, exchange",p:"v"},
    {i:439,u:5,s:1,r:"かえる",w:"返る",v:"được trả lại, quay về",e:"return (come back)",p:"v"},
    {i:440,u:5,s:1,r:"かえす",w:"返す",v:"trả lại",e:"return (give back)",p:"v"},
    {i:441,u:5,s:1,r:"ゆずる",w:"譲る",v:"nhường",e:"give up (seat); let have",p:"v"},
    {i:442,u:5,s:1,r:"たすかる",w:"助かる",v:"được cứu; đỡ, nhờ thế mà tiện",e:"survive; be helpful",p:"v"},
    {i:443,u:5,s:1,r:"たすける",w:"助ける",v:"cứu; giúp đỡ",e:"save; help",p:"v"},
    {i:444,u:5,s:1,r:"いじめる",w:"いじめる",v:"bắt nạt, ức hiếp",e:"bully",p:"v"},
    {i:445,u:5,s:1,r:"だます",w:"だます",v:"lừa, lừa gạt",e:"deceive",p:"v"},
    {i:446,u:5,s:1,r:"ぬすむ",w:"盗む",v:"trộm, ăn cắp",e:"steal",p:"v"},
    {i:447,u:5,s:1,r:"ささる",w:"刺さる",v:"bị đâm, cắm vào",e:"be stuck in",p:"v"},
    {i:448,u:5,s:1,r:"さす",w:"刺す",v:"đâm, chích (côn trùng)",e:"stick, stab",p:"v"},
    {i:449,u:5,s:1,r:"ころす",w:"殺す",v:"giết",e:"kill",p:"v"},
    {i:450,u:5,s:1,r:"かくれる",w:"隠れる",v:"ẩn nấp, trốn",e:"hide (intr.)",p:"v"},
    {i:451,u:5,s:1,r:"かくす",w:"隠す",v:"giấu, che giấu",e:"hide (tr.)",p:"v"},
    {i:452,u:5,s:1,r:"うまる",w:"埋まる",v:"bị chôn vùi, bị lấp",e:"be buried",p:"v"},
    {i:453,u:5,s:1,r:"うめる",w:"埋める",v:"chôn, lấp; điền (chỗ trống)",e:"bury; fill",p:"v"},
    {i:454,u:5,s:1,r:"かこむ",w:"囲む",v:"vây quanh, khoanh tròn",e:"surround, circle",p:"v"},
    {i:455,u:5,s:1,r:"つまる",w:"詰まる",v:"bị nghẹt, bị nhồi; sát lại",e:"be packed; be clogged",p:"v"},
    {i:456,u:5,s:1,r:"つめる",w:"詰める",v:"nhồi, nhét; rút ngắn",e:"pack, fill; shorten",p:"v"},
    {i:457,u:5,s:1,r:"ひらく",w:"開く",v:"mở; nở; mở (tiệc)",e:"open; bloom",p:"v"},
    {i:458,u:5,s:1,r:"とじる",w:"閉じる",v:"đóng, khép, ngậm",e:"close",p:"v"},
    {i:459,u:5,s:1,r:"とぶ",w:"飛ぶ",v:"bay; nhảy cóc",e:"fly; skip",p:"v"},
    {i:460,u:5,s:1,r:"とばす",w:"飛ばす",v:"làm bay; bỏ qua (cách quãng)",e:"let fly; skip",p:"v"},
    {i:461,u:5,s:2,r:"ふる",w:"振る",v:"vẫy; rắc; từ chối, lắc",e:"wave; sprinkle; reject",p:"v"},
    {i:462,u:5,s:2,r:"めくる",w:"めくる",v:"lật (trang)",e:"turn over (page)",p:"v"},
    {i:463,u:5,s:2,r:"みかける",w:"見かける",v:"bắt gặp, trông thấy",e:"see, come across",p:"v"},
    {i:464,u:5,s:2,r:"たしかめる",w:"確かめる",v:"xác nhận, kiểm chứng",e:"check, confirm",p:"v"},
    {i:465,u:5,s:2,r:"ためす",w:"試す",v:"thử, kiểm thử",e:"try, test",p:"v"},
    {i:466,u:5,s:2,r:"くりかえす",w:"繰り返す",v:"lặp lại",e:"repeat",p:"v"},
    {i:467,u:5,s:2,r:"やくす",w:"訳す",v:"dịch (ngôn ngữ)",e:"translate",p:"v"},
    {i:468,u:5,s:2,r:"おこなう",w:"行う",v:"tiến hành, thực hiện",e:"hold (event), do",p:"v"},
    {i:469,u:5,s:2,r:"まちがう",w:"間違う",v:"sai, nhầm",e:"be wrong",p:"v"},
    {i:470,u:5,s:2,r:"まちがえる",w:"間違える",v:"làm sai, nhầm lẫn",e:"mistake for",p:"v"},
    {i:471,u:5,s:2,r:"ゆるす",w:"許す",v:"tha thứ; cho phép",e:"forgive; allow",p:"v"},
    {i:472,u:5,s:2,r:"なれる",w:"慣れる",v:"quen",e:"be accustomed",p:"v"},
    {i:473,u:5,s:2,r:"ならす",w:"慣らす",v:"làm cho quen",e:"accustom",p:"v"},
    {i:474,u:5,s:2,r:"たつ",w:"立つ",v:"đứng; dựng đứng",e:"stand",p:"v"},
    {i:475,u:5,s:2,r:"たてる",w:"立てる",v:"dựng; lập (kế hoạch)",e:"put up; make (a plan)",p:"v"},
    {i:476,u:5,s:2,r:"たつ",w:"建つ",v:"được xây",e:"be constructed",p:"v"},
    {i:477,u:5,s:2,r:"たてる",w:"建てる",v:"xây dựng",e:"construct, build",p:"v"},
    {i:478,u:5,s:2,r:"そだつ",w:"育つ",v:"lớn lên, trưởng thành",e:"grow up",p:"v"},
    {i:479,u:5,s:2,r:"そだてる",w:"育てる",v:"nuôi dưỡng, trồng",e:"raise, grow",p:"v"},
    {i:480,u:5,s:2,r:"はえる",w:"生える",v:"mọc (tóc, răng, cỏ)",e:"(hair/tooth) grows",p:"v"},
    {i:481,u:5,s:2,r:"はやす",w:"生やす",v:"để mọc, nuôi (râu)",e:"grow (a beard)",p:"v"},
    {i:482,u:5,s:2,r:"よごれる",w:"汚れる",v:"bị bẩn",e:"be dirty",p:"v"},
    {i:483,u:5,s:2,r:"よごす",w:"汚す",v:"làm bẩn, làm ô nhiễm",e:"dirty, pollute",p:"v"},
    {i:484,u:5,s:2,r:"こわれる",w:"壊れる",v:"bị hỏng, vỡ",e:"break (intr.)",p:"v"},
    {i:485,u:5,s:2,r:"こわす",w:"壊す",v:"làm hỏng, phá; làm hại (sức khỏe)",e:"break; damage",p:"v"},
    {i:486,u:5,s:2,r:"われる",w:"割れる",v:"vỡ, nứt",e:"break, be split",p:"v"},
    {i:487,u:5,s:2,r:"わる",w:"割る",v:"làm vỡ; chia",e:"break; divide",p:"v"},
    {i:488,u:5,s:2,r:"おれる",w:"折れる",v:"gãy",e:"break, snap",p:"v"},
    {i:489,u:5,s:2,r:"おる",w:"折る",v:"bẻ gãy; gấp",e:"break; fold",p:"v"},
    {i:490,u:5,s:2,r:"やぶれる",w:"破れる",v:"rách",e:"be ripped",p:"v"},
    {i:491,u:5,s:2,r:"やぶる",w:"破る",v:"xé; phá vỡ (lời hứa, kỷ lục)",e:"rip; break (a record)",p:"v"},
    {i:492,u:5,s:2,r:"まがる",w:"曲がる",v:"rẽ, quẹo; cong",e:"turn, curve",p:"v"},
    {i:493,u:5,s:2,r:"まげる",w:"曲げる",v:"bẻ cong, uốn",e:"bend",p:"v"},
    {i:494,u:5,s:2,r:"はずれる",w:"外れる",v:"tuột ra; trật, sai; bị loại",e:"come off; be wrong",p:"v"},
    {i:495,u:5,s:2,r:"はずす",w:"外す",v:"tháo ra; làm trật; loại bỏ",e:"take off; exclude",p:"v"},
    {i:496,u:5,s:2,r:"ゆれる",w:"揺れる",v:"rung, lắc, lung lay",e:"shake, waver",p:"v"},
    {i:497,u:5,s:2,r:"ゆらす",w:"揺らす",v:"làm lắc, đung đưa",e:"shake (tr.)",p:"v"},
    {i:498,u:5,s:2,r:"ながれる",w:"流れる",v:"chảy, trôi; lan truyền",e:"flow; drift",p:"v"},
    {i:499,u:5,s:2,r:"ながす",w:"流す",v:"làm chảy, xả; bật (nhạc)",e:"flush; play (music)",p:"v"},
    {i:500,u:5,s:2,r:"ぬれる",w:"濡れる",v:"bị ướt",e:"become wet",p:"v"},
    {i:501,u:5,s:2,r:"ぬらす",w:"濡らす",v:"làm ướt",e:"wet, soak",p:"v"},
    {i:502,u:5,s:2,r:"まよう",w:"迷う",v:"lạc; phân vân, do dự",e:"get lost; vacillate",p:"v"},
    {i:503,u:5,s:2,r:"なやむ",w:"悩む",v:"khổ tâm, trăn trở, phiền muộn",e:"be troubled",p:"v"},
    {i:504,u:5,s:2,r:"あわてる",w:"慌てる",v:"hoảng, luống cuống, cuống cuồng",e:"be flustered, panic",p:"v"},
    {i:505,u:5,s:2,r:"さめる",w:"覚める",v:"tỉnh giấc, tỉnh (rượu)",e:"wake up; sober up",p:"v"},
    {i:506,u:5,s:2,r:"さます",w:"覚ます",v:"làm tỉnh, đánh thức",e:"wake up (tr.)",p:"v"},
    {i:507,u:5,s:2,r:"ねむる",w:"眠る",v:"ngủ",e:"sleep",p:"v"},
    {i:508,u:5,s:2,r:"いのる",w:"祈る",v:"cầu nguyện, cầu chúc",e:"pray",p:"v"},
    {i:509,u:5,s:2,r:"いわう",w:"祝う",v:"chúc mừng, ăn mừng",e:"celebrate",p:"v"},
    {i:510,u:5,s:2,r:"かんじる",w:"感じる",v:"cảm thấy, cảm nhận",e:"feel",p:"v"},
    {i:511,u:6,s:1,r:"クラスメート",w:"クラスメート",v:"bạn cùng lớp",e:"classmate",p:"k"},
    {i:512,u:6,s:1,r:"グループ",w:"グループ",v:"nhóm",e:"group",p:"k"},
    {i:513,u:6,s:1,r:"チーム",w:"チーム",v:"đội, nhóm",e:"team",p:"k"},
    {i:514,u:6,s:1,r:"プロフェッショナル",w:"プロフェッショナル",v:"chuyên nghiệp; dân chuyên (プロ)",e:"professional",p:"k"},
    {i:515,u:6,s:1,r:"アマチュア",w:"アマチュア",v:"nghiệp dư (アマ)",e:"amateur",p:"k"},
    {i:516,u:6,s:1,r:"トレーニング",w:"トレーニング",v:"luyện tập, rèn luyện",e:"training",p:"k"},
    {i:517,u:6,s:1,r:"マッサージ",w:"マッサージ",v:"mát-xa",e:"massage",p:"k"},
    {i:518,u:6,s:1,r:"アドバイス",w:"アドバイス",v:"lời khuyên",e:"advice",p:"k"},
    {i:519,u:6,s:1,r:"アイデア",w:"アイデア",v:"ý tưởng (アイディア)",e:"idea",p:"k"},
    {i:520,u:6,s:1,r:"トップ",w:"トップ",v:"đứng đầu, hàng đầu",e:"top, first",p:"k"},
    {i:521,u:6,s:1,r:"スピード",w:"スピード",v:"tốc độ",e:"speed",p:"k"},
    {i:522,u:6,s:1,r:"ラッシュ",w:"ラッシュ",v:"giờ cao điểm; sự đổ xô",e:"rush, rush hour",p:"k"},
    {i:523,u:6,s:1,r:"バイク",w:"バイク",v:"xe máy",e:"motorcycle",p:"k"},
    {i:524,u:6,s:1,r:"ヘルメット",w:"ヘルメット",v:"mũ bảo hiểm",e:"helmet",p:"k"},
    {i:525,u:6,s:1,r:"コンタクトレンズ",w:"コンタクトレンズ",v:"kính áp tròng (コンタクト)",e:"contact lens",p:"k"},
    {i:526,u:6,s:1,r:"ガラス",w:"ガラス",v:"kính, thủy tinh",e:"glass, pane",p:"k"},
    {i:527,u:6,s:1,r:"プラスチック",w:"プラスチック",v:"nhựa",e:"plastic",p:"k"},
    {i:528,u:6,s:1,r:"ベランダ",w:"ベランダ",v:"ban công",e:"balcony",p:"k"},
    {i:529,u:6,s:1,r:"ペット",w:"ペット",v:"thú cưng",e:"pet",p:"k"},
    {i:530,u:6,s:1,r:"ベンチ",w:"ベンチ",v:"ghế dài, ghế băng",e:"bench",p:"k"},
    {i:531,u:6,s:1,r:"デザイン",w:"デザイン",v:"thiết kế",e:"design",p:"k"},
    {i:532,u:6,s:1,r:"バーゲンセール",w:"バーゲンセール",v:"đợt giảm giá (バーゲン)",e:"sale",p:"k"},
    {i:533,u:6,s:1,r:"パート",w:"パート",v:"việc làm bán thời gian; bè (nhạc)",e:"part-time job; part",p:"k"},
    {i:534,u:6,s:1,r:"コンビニエンスストア",w:"コンビニエンスストア",v:"cửa hàng tiện lợi (コンビニ)",e:"convenience store",p:"k"},
    {i:535,u:6,s:1,r:"レジ",w:"レジ",v:"quầy thu ngân",e:"cash register",p:"k"},
    {i:536,u:6,s:1,r:"レシート",w:"レシート",v:"hóa đơn, biên lai",e:"receipt",p:"k"},
    {i:537,u:6,s:1,r:"インスタント",w:"インスタント",v:"ăn liền, tức thì",e:"instant",p:"k"},
    {i:538,u:6,s:1,r:"ファストフード",w:"ファストフード",v:"đồ ăn nhanh",e:"fast food",p:"k"},
    {i:539,u:6,s:1,r:"フルーツ",w:"フルーツ",v:"trái cây",e:"fruit",p:"k"},
    {i:540,u:6,s:1,r:"デザート",w:"デザート",v:"món tráng miệng",e:"dessert",p:"k"},
    {i:541,u:6,s:1,r:"インターネット",w:"インターネット",v:"mạng internet",e:"Internet",p:"k"},
    {i:542,u:6,s:1,r:"チャイム",w:"チャイム",v:"chuông báo",e:"chime",p:"k"},
    {i:543,u:6,s:1,r:"アナウンス",w:"アナウンス",v:"thông báo (phát thanh)",e:"announcement",p:"k"},
    {i:544,u:6,s:1,r:"メッセージ",w:"メッセージ",v:"tin nhắn, thông điệp",e:"message",p:"k"},
    {i:545,u:6,s:1,r:"パンフレット",w:"パンフレット",v:"tờ rơi, cuốn giới thiệu",e:"pamphlet",p:"k"},
    {i:546,u:6,s:1,r:"カード",w:"カード",v:"thẻ",e:"card",p:"k"},
    {i:547,u:6,s:1,r:"インタビュー",w:"インタビュー",v:"phỏng vấn (báo chí)",e:"interview",p:"k"},
    {i:548,u:6,s:1,r:"アンケート",w:"アンケート",v:"bảng khảo sát, phiếu thăm dò",e:"questionnaire",p:"k"},
    {i:549,u:6,s:1,r:"データ",w:"データ",v:"dữ liệu",e:"data",p:"k"},
    {i:550,u:6,s:1,r:"パーセント",w:"パーセント",v:"phần trăm",e:"percent",p:"k"},
    {i:551,u:7,s:1,r:"こい",w:"濃い",v:"đậm, đặc, sẫm",e:"dark, strong, thick",p:"a"},
    {i:552,u:7,s:1,r:"うすい",w:"薄い",v:"nhạt, mỏng, loãng",e:"light, thin, weak",p:"a"},
    {i:553,u:7,s:1,r:"すっぱい",w:"酸っぱい",v:"chua",e:"sour",p:"a"},
    {i:554,u:7,s:1,r:"くさい",w:"臭い",v:"hôi, thối",e:"stinky",p:"a"},
    {i:555,u:7,s:1,r:"おかしい",w:"おかしい",v:"buồn cười; kỳ lạ, lạ",e:"amusing; strange",p:"a"},
    {i:556,u:7,s:1,r:"かっこいい",w:"かっこいい",v:"ngầu, đẹp, bảnh",e:"cool, nifty",p:"a"},
    {i:557,u:7,s:1,r:"うまい",w:"うまい",v:"giỏi, khéo; ngon",e:"skillful; tasty",p:"a"},
    {i:558,u:7,s:1,r:"したしい",w:"親しい",v:"thân thiết",e:"intimate",p:"a"},
    {i:559,u:7,s:1,r:"くわしい",w:"詳しい",v:"chi tiết, tường tận; am hiểu",e:"detailed; knowledgeable",p:"a"},
    {i:560,u:7,s:1,r:"こまかい",w:"細かい",v:"nhỏ, vụn; tỉ mỉ; (tiền) lẻ",e:"fine; detailed; small",p:"a"},
    {i:561,u:7,s:1,r:"あさい",w:"浅い",v:"nông, cạn",e:"shallow",p:"a"},
    {i:562,u:7,s:1,r:"かたい",w:"固い",v:"cứng, chắc; cứng nhắc",e:"hard, firm, stiff",p:"a"},
    {i:563,u:7,s:1,r:"ぬるい",w:"ぬるい",v:"âm ấm, nguội",e:"lukewarm",p:"a"},
    {i:564,u:7,s:1,r:"まぶしい",w:"まぶしい",v:"chói, chói mắt",e:"dazzling",p:"a"},
    {i:565,u:7,s:1,r:"むしあつい",w:"蒸し暑い",v:"oi bức, nóng ẩm",e:"sultry",p:"a"},
    {i:566,u:7,s:1,r:"せいけつな",w:"清潔な",v:"sạch sẽ",e:"clean",p:"a"},
    {i:567,u:7,s:1,r:"しんせんな",w:"新鮮な",v:"tươi, tươi mới",e:"fresh",p:"a"},
    {i:568,u:7,s:1,r:"ゆたかな",w:"豊かな",v:"phong phú, giàu có, dồi dào",e:"abundant, rich",p:"a"},
    {i:569,u:7,s:1,r:"りっぱな",w:"立派な",v:"đẹp đẽ, lộng lẫy, đường hoàng",e:"splendid, grand",p:"a"},
    {i:570,u:7,s:1,r:"せいかくな",w:"正確な",v:"chính xác",e:"exact, accurate",p:"a"},
    {i:571,u:7,s:1,r:"たしかな",w:"確かな",v:"chắc chắn, xác thực",e:"definite, certain",p:"a"},
    {i:572,u:7,s:1,r:"じゅうような",w:"重要な",v:"quan trọng",e:"important",p:"a"},
    {i:573,u:7,s:1,r:"ひつような",w:"必要な",v:"cần thiết",e:"necessary",p:"a"},
    {i:574,u:7,s:1,r:"もったいない",w:"もったいない",v:"lãng phí, phí phạm (tiếc của)",e:"wasteful",p:"a"},
    {i:575,u:7,s:1,r:"すごい",w:"すごい",v:"tuyệt; kinh khủng, ghê gớm",e:"tremendous, incredible",p:"a"},
    {i:576,u:7,s:1,r:"ひどい",w:"ひどい",v:"tệ, tồi tệ; quá đáng, dữ dội",e:"terrible; awful",p:"a"},
    {i:577,u:7,s:1,r:"はげしい",w:"激しい",v:"dữ dội, mãnh liệt",e:"violent, intense",p:"a"},
    {i:578,u:7,s:1,r:"そっくりな",w:"そっくりな",v:"giống hệt",e:"look-alike",p:"a"},
    {i:579,u:7,s:1,r:"きゅうな",w:"急な",v:"đột ngột; gấp; dốc đứng",e:"sudden; urgent; steep",p:"a"},
    {i:580,u:7,s:1,r:"てきとうな",w:"適当な",v:"thích hợp; qua loa, đại khái",e:"suitable; irresponsible",p:"a"},
    {i:581,u:7,s:1,r:"とくべつな",w:"特別な",v:"đặc biệt",e:"special",p:"a"},
    {i:582,u:7,s:1,r:"かんぜんな",w:"完全な",v:"hoàn toàn, hoàn chỉnh",e:"complete, total",p:"a"},
    {i:583,u:7,s:1,r:"さかんな",w:"盛んな",v:"thịnh vượng, sôi nổi, phát đạt",e:"flourishing",p:"a"},
    {i:584,u:7,s:1,r:"さまざまな",w:"様々な",v:"đa dạng, muôn vẻ",e:"various",p:"a"},
    {i:585,u:7,s:1,r:"かのうな",w:"可能な",v:"khả thi, có thể",e:"possible",p:"a"},
    {i:586,u:7,s:1,r:"ふかのうな",w:"不可能な",v:"bất khả thi, không thể",e:"impossible",p:"a"},
    {i:587,u:7,s:1,r:"きほんてきな",w:"基本的な",v:"cơ bản",e:"basic",p:"a"},
    {i:588,u:7,s:1,r:"こくさいてきな",w:"国際的な",v:"mang tính quốc tế",e:"international",p:"a"},
    {i:589,u:7,s:1,r:"ばらばらな",w:"ばらばらな",v:"rời rạc, tản mác, mỗi nơi một kiểu",e:"scattered",p:"a"},
    {i:590,u:7,s:1,r:"ぼろぼろな",w:"ぼろぼろな",v:"rách rưới, tả tơi, nát bươm",e:"ragged, worn out",p:"a"},
    {i:591,u:8,s:1,r:"ひじょうに",w:"非常に",v:"vô cùng, rất, cực kỳ",e:"very, extremely",p:"adv"},
    {i:592,u:8,s:1,r:"たいへん",w:"大変",v:"rất, vô cùng",e:"terribly, greatly",p:"adv"},
    {i:593,u:8,s:1,r:"ほとんど",w:"ほとんど",v:"hầu hết; hầu như (không)",e:"nearly, hardly",p:"adv"},
    {i:594,u:8,s:1,r:"だいたい",w:"大体",v:"đại khái, hầu như; khoảng",e:"mostly, about",p:"adv"},
    {i:595,u:8,s:1,r:"かなり",w:"かなり",v:"khá, tương đối",e:"fairly, quite",p:"adv"},
    {i:596,u:8,s:1,r:"ずいぶん",w:"ずいぶん",v:"khá nhiều, đáng kể",e:"considerably",p:"adv"},
    {i:597,u:8,s:1,r:"けっこう",w:"けっこう",v:"khá, kha khá",e:"pretty, fairly",p:"adv"},
    {i:598,u:8,s:1,r:"だいぶ",w:"大分",v:"khá, kha khá, nhiều",e:"mostly, fairly",p:"adv"},
    {i:599,u:8,s:1,r:"もっと",w:"もっと",v:"hơn nữa, thêm",e:"more",p:"adv"},
    {i:600,u:8,s:1,r:"すっかり",w:"すっかり",v:"hoàn toàn, sạch sẽ",e:"completely",p:"adv"},
    {i:601,u:8,s:1,r:"いっぱい",w:"一杯",v:"đầy, nhiều; một cốc",e:"full",p:"adv"},
    {i:602,u:8,s:1,r:"ぎりぎり",w:"ぎりぎり",v:"sát nút, vừa kịp, sít sao",e:"barely, last minute",p:"adv"},
    {i:603,u:8,s:1,r:"ぴったり",w:"ぴったり",v:"vừa khít, khớp, đúng",e:"exactly; perfectly",p:"adv"},
    {i:604,u:8,s:1,r:"たいてい",w:"たいてい",v:"thường thường, đa phần",e:"usually, mostly",p:"adv"},
    {i:605,u:8,s:1,r:"どうじに",w:"同時に",v:"đồng thời, cùng lúc",e:"simultaneously",p:"adv"},
    {i:606,u:8,s:1,r:"まえもって",w:"前もって",v:"trước, từ trước",e:"in advance",p:"adv"},
    {i:607,u:8,s:1,r:"すぐに",w:"すぐに",v:"ngay, ngay lập tức",e:"immediately",p:"adv"},
    {i:608,u:8,s:1,r:"もうすぐ",w:"もうすぐ",v:"sắp, sắp tới",e:"soon",p:"adv"},
    {i:609,u:8,s:1,r:"とつぜん",w:"突然",v:"đột nhiên, bất chợt",e:"suddenly",p:"adv"},
    {i:610,u:8,s:1,r:"あっというまに",w:"あっという間に",v:"trong nháy mắt, chớp mắt",e:"in a flash",p:"adv"},
    {i:611,u:8,s:1,r:"いつのまにか",w:"いつの間にか",v:"tự lúc nào không hay",e:"before one knows it",p:"adv"},
    {i:612,u:8,s:1,r:"しばらく",w:"しばらく",v:"một lát; một thời gian",e:"for a while",p:"adv"},
    {i:613,u:8,s:1,r:"ずっと",w:"ずっと",v:"suốt, mãi; hơn hẳn",e:"the whole time; by far",p:"adv"},
    {i:614,u:8,s:1,r:"あいかわらず",w:"相変わらず",v:"như mọi khi, vẫn như cũ",e:"as usual, unchanged",p:"adv"},
    {i:615,u:8,s:1,r:"つぎつぎに",w:"次々に",v:"lần lượt, liên tiếp",e:"one after another",p:"adv"},
    {i:616,u:8,s:1,r:"どんどん",w:"どんどん",v:"ào ào, vùn vụt, nhanh chóng",e:"steadily, more and more",p:"adv"},
    {i:617,u:8,s:1,r:"ますます",w:"ますます",v:"ngày càng, càng thêm",e:"increasingly",p:"adv"},
    {i:618,u:8,s:1,r:"やっと",w:"やっと",v:"cuối cùng (cũng); vất vả mới",e:"finally, barely",p:"adv"},
    {i:619,u:8,s:1,r:"とうとう",w:"とうとう",v:"rốt cuộc, cuối cùng",e:"finally, in the end",p:"adv"},
    {i:620,u:8,s:1,r:"ついに",w:"ついに",v:"cuối cùng, rốt cuộc",e:"finally, at long last",p:"adv"},
    {i:621,u:8,s:1,r:"もちろん",w:"もちろん",v:"tất nhiên, dĩ nhiên",e:"of course",p:"adv"},
    {i:622,u:8,s:1,r:"やはり",w:"やはり",v:"quả nhiên, vẫn, đúng là",e:"as expected, still",p:"adv"},
    {i:623,u:8,s:1,r:"きっと",w:"きっと",v:"chắc chắn, nhất định",e:"certainly, surely",p:"adv"},
    {i:624,u:8,s:1,r:"ぜひ",w:"ぜひ",v:"nhất định, bằng mọi giá",e:"by all means",p:"adv"},
    {i:625,u:8,s:1,r:"なるべく",w:"なるべく",v:"càng… càng tốt, cố gắng",e:"as much as possible",p:"adv"},
    {i:626,u:8,s:1,r:"あんがい",w:"案外",v:"ngoài dự đoán, không ngờ",e:"unexpectedly",p:"adv"},
    {i:627,u:8,s:1,r:"もしかすると",w:"もしかすると",v:"biết đâu, có lẽ, không chừng",e:"maybe, perhaps",p:"adv"},
    {i:628,u:8,s:1,r:"まさか",w:"まさか",v:"không lẽ, chẳng lẽ nào",e:"no way",p:"adv"},
    {i:629,u:8,s:1,r:"うっかり",w:"うっかり",v:"lơ đãng, sơ ý, vô tình",e:"absent-mindedly",p:"adv"},
    {i:630,u:8,s:1,r:"つい",w:"つい",v:"lỡ, vô tình, trót",e:"in spite of oneself",p:"adv"},
    {i:631,u:8,s:1,r:"おもわず",w:"思わず",v:"bất giác, theo phản xạ",e:"spontaneously",p:"adv"},
    {i:632,u:8,s:1,r:"ほっと",w:"ほっと",v:"nhẹ nhõm, thở phào",e:"relieved",p:"adv"},
    {i:633,u:8,s:1,r:"いらいら",w:"いらいら",v:"bực bội, sốt ruột, cáu",e:"irritated",p:"adv"},
    {i:634,u:8,s:1,r:"のんびり",w:"のんびり",v:"thong thả, thư thái",e:"leisurely",p:"adv"},
    {i:635,u:8,s:1,r:"じつは",w:"実は",v:"thực ra, thật ra",e:"to tell the truth, actually",p:"adv"},
    {i:636,u:9,s:1,r:"どくしょ",w:"読書",v:"đọc sách",e:"reading",p:"n"},
    {i:637,u:9,s:1,r:"えんそう",w:"演奏",v:"biểu diễn nhạc, tấu nhạc",e:"musical performance",p:"n"},
    {i:638,u:9,s:1,r:"げいじゅつ",w:"芸術",v:"nghệ thuật",e:"art",p:"n"},
    {i:639,u:9,s:1,r:"けんさ",w:"検査",v:"kiểm tra, khám (bệnh)",e:"inspection, examination",p:"n"},
    {i:640,u:9,s:1,r:"けつえき",w:"血液",v:"máu, huyết",e:"blood",p:"n"},
    {i:641,u:9,s:1,r:"ちりょう",w:"治療",v:"điều trị, chữa trị",e:"treatment",p:"n"},
    {i:642,u:9,s:1,r:"しょうじょう",w:"症状",v:"triệu chứng",e:"symptom",p:"n"},
    {i:643,u:9,s:1,r:"よぼう",w:"予防",v:"phòng ngừa",e:"prevention",p:"n"},
    {i:644,u:9,s:1,r:"えいよう",w:"栄養",v:"dinh dưỡng",e:"nutrition",p:"n"},
    {i:645,u:9,s:1,r:"しゅじゅつ",w:"手術",v:"phẫu thuật",e:"surgery",p:"n"},
    {i:646,u:9,s:1,r:"しぼう",w:"死亡",v:"tử vong, cái chết",e:"death",p:"n"},
    {i:647,u:9,s:1,r:"いのち",w:"命",v:"sinh mạng, tính mạng",e:"life",p:"n"},
    {i:648,u:9,s:1,r:"いっしょう",w:"一生",v:"cả đời, suốt đời",e:"whole life, forever",p:"n"},
    {i:649,u:9,s:1,r:"ごかい",w:"誤解",v:"hiểu lầm",e:"misunderstanding",p:"n"},
    {i:650,u:9,s:1,r:"こうかい",w:"後悔",v:"hối hận",e:"regret",p:"n"},
    {i:651,u:9,s:1,r:"わけ",w:"訳",v:"lý do; ý nghĩa, lẽ",e:"reason, meaning",p:"n"},
    {i:652,u:9,s:1,r:"たいど",w:"態度",v:"thái độ",e:"attitude",p:"n"},
    {i:653,u:9,s:1,r:"くせ",w:"癖",v:"thói quen (xấu), tật",e:"habit",p:"n"},
    {i:654,u:9,s:1,r:"れいぎ",w:"礼儀",v:"lễ nghĩa, lễ phép",e:"etiquette",p:"n"},
    {i:655,u:9,s:1,r:"もんく",w:"文句",v:"lời phàn nàn; câu chữ",e:"complaint; words",p:"n"},
    {i:656,u:9,s:1,r:"ひょうじょう",w:"表情",v:"biểu cảm, nét mặt",e:"facial expression",p:"n"},
    {i:657,u:9,s:1,r:"ひょうめん",w:"表面",v:"bề mặt",e:"surface",p:"n"},
    {i:658,u:9,s:1,r:"きんえん",w:"禁煙",v:"cấm hút thuốc; cai thuốc",e:"no smoking",p:"n"},
    {i:659,u:9,s:1,r:"きんし",w:"禁止",v:"cấm, sự cấm",e:"prohibition",p:"n"},
    {i:660,u:9,s:1,r:"かんせい",w:"完成",v:"hoàn thành",e:"completion",p:"n"},
    {i:661,u:9,s:1,r:"かだい",w:"課題",v:"vấn đề; bài tập, đề tài",e:"issue, assignment",p:"n"},
    {i:662,u:9,s:1,r:"れいがい",w:"例外",v:"ngoại lệ",e:"exception",p:"n"},
    {i:663,u:9,s:1,r:"きほん",w:"基本",v:"cơ bản, nền tảng",e:"fundamentals, basis",p:"n"},
    {i:664,u:9,s:1,r:"きろく",w:"記録",v:"ghi chép; kỷ lục",e:"record",p:"n"},
    {i:665,u:9,s:1,r:"じょうたい",w:"状態",v:"trạng thái, tình trạng",e:"condition, state",p:"n"},
    {i:666,u:9,s:1,r:"できごと",w:"出来事",v:"sự việc, sự kiện",e:"happening, event",p:"n"},
    {i:667,u:9,s:1,r:"ばめん",w:"場面",v:"tình huống, cảnh (phim)",e:"situation, scene",p:"n"},
    {i:668,u:9,s:1,r:"きかい",w:"機会",v:"cơ hội",e:"opportunity",p:"n"},
    {i:669,u:9,s:1,r:"きょり",w:"距離",v:"khoảng cách",e:"distance",p:"n"},
    {i:670,u:9,s:1,r:"ていあん",w:"提案",v:"đề xuất, đề án",e:"proposal",p:"n"},
    {i:671,u:9,s:1,r:"やりとり",w:"やり取り",v:"sự trao đổi (qua lại)",e:"exchange",p:"n"},
    {i:672,u:9,s:1,r:"ちしき",w:"知識",v:"kiến thức",e:"knowledge",p:"n"},
    {i:673,u:9,s:1,r:"じつりょく",w:"実力",v:"thực lực, năng lực",e:"ability",p:"n"},
    {i:674,u:9,s:1,r:"しゅだん",w:"手段",v:"phương tiện, biện pháp",e:"means",p:"n"},
    {i:675,u:9,s:1,r:"だいひょう",w:"代表",v:"đại diện, tiêu biểu",e:"representative",p:"n"},
    {i:676,u:9,s:2,r:"えいきょう",w:"影響",v:"ảnh hưởng",e:"influence",p:"n"},
    {i:677,u:9,s:2,r:"こうか",w:"効果",v:"hiệu quả",e:"effect",p:"n"},
    {i:678,u:9,s:2,r:"いんしょう",w:"印象",v:"ấn tượng",e:"impression",p:"n"},
    {i:679,u:9,s:2,r:"しるし",w:"印",v:"dấu hiệu, ký hiệu",e:"mark, sign",p:"n"},
    {i:680,u:9,s:2,r:"あいず",w:"合図",v:"tín hiệu, sự ra hiệu",e:"signal",p:"n"},
    {i:681,u:9,s:2,r:"きょうつう",w:"共通",v:"chung, điểm chung",e:"common, shared",p:"n"},
    {i:682,u:9,s:2,r:"きょうちょう",w:"強調",v:"sự nhấn mạnh",e:"emphasis",p:"n"},
    {i:683,u:9,s:2,r:"しょうりゃく",w:"省略",v:"lược bỏ, giản lược",e:"abbreviation, omission",p:"n"},
    {i:684,u:9,s:2,r:"ちょうせん",w:"挑戦",v:"thử thách, thách thức",e:"challenge",p:"n"},
    {i:685,u:9,s:2,r:"やるき",w:"やる気",v:"động lực, sự hăng hái",e:"motivation",p:"n"},
    {i:686,u:9,s:2,r:"ゆうき",w:"勇気",v:"dũng khí, can đảm",e:"courage",p:"n"},
    {i:687,u:9,s:2,r:"しかく",w:"資格",v:"tư cách; chứng chỉ, bằng cấp",e:"qualification",p:"n"},
    {i:688,u:9,s:2,r:"しんせい",w:"申請",v:"đơn xin, sự thỉnh cầu",e:"application",p:"n"},
    {i:689,u:9,s:2,r:"ほんにん",w:"本人",v:"bản thân người đó, đương sự",e:"the person in question",p:"n"},
    {i:690,u:9,s:2,r:"けいやく",w:"契約",v:"hợp đồng",e:"contract",p:"n"},
    {i:691,u:9,s:2,r:"しょうめい",w:"証明",v:"chứng minh",e:"proof",p:"n"},
    {i:692,u:9,s:2,r:"へんこう",w:"変更",v:"thay đổi, biến đổi (kế hoạch)",e:"change",p:"n"},
    {i:693,u:9,s:2,r:"ほぞん",w:"保存",v:"bảo quản, lưu trữ",e:"preservation",p:"n"},
    {i:694,u:9,s:2,r:"ほご",w:"保護",v:"bảo vệ, bảo hộ",e:"protection",p:"n"},
    {i:695,u:9,s:2,r:"かんきょう",w:"環境",v:"môi trường",e:"environment",p:"n"},
    {i:696,u:9,s:2,r:"しげん",w:"資源",v:"tài nguyên",e:"resources",p:"n"},
    {i:697,u:9,s:2,r:"ふそく",w:"不足",v:"thiếu hụt",e:"shortage",p:"n"},
    {i:698,u:9,s:2,r:"へいきん",w:"平均",v:"trung bình",e:"average",p:"n"},
    {i:699,u:9,s:2,r:"わりあい",w:"割合",v:"tỷ lệ; tương đối",e:"ratio; relatively",p:"n"},
    {i:700,u:9,s:2,r:"しょうばい",w:"商売",v:"buôn bán, kinh doanh",e:"business",p:"n"},
    {i:701,u:9,s:2,r:"しょうひん",w:"商品",v:"hàng hóa, sản phẩm",e:"product",p:"n"},
    {i:702,u:9,s:2,r:"しつ",w:"質",v:"chất lượng",e:"quality",p:"n"},
    {i:703,u:9,s:2,r:"かた",w:"型",v:"kiểu, loại, mẫu",e:"model, type",p:"n"},
    {i:704,u:9,s:2,r:"せいさん",w:"生産",v:"sản xuất",e:"production",p:"n"},
    {i:705,u:9,s:2,r:"しょうひ",w:"消費",v:"tiêu thụ, tiêu dùng",e:"consumption",p:"n"},
    {i:706,u:9,s:2,r:"ぶっか",w:"物価",v:"vật giá, giá cả",e:"prices",p:"n"},
    {i:707,u:9,s:2,r:"とうさん",w:"倒産",v:"phá sản",e:"bankruptcy",p:"n"},
    {i:708,u:9,s:2,r:"けいたい",w:"携帯",v:"mang theo; điện thoại di động",e:"carrying; mobile",p:"n"},
    {i:709,u:9,s:2,r:"げんだい",w:"現代",v:"hiện đại, thời nay",e:"the present age",p:"n"},
    {i:710,u:9,s:2,r:"せいき",w:"世紀",v:"thế kỷ",e:"century",p:"n"},
    {i:711,u:9,s:2,r:"ぶんか",w:"文化",v:"văn hóa",e:"culture",p:"n"},
    {i:712,u:9,s:2,r:"とし",w:"都市",v:"đô thị, thành phố",e:"city",p:"n"},
    {i:713,u:9,s:2,r:"ちほう",w:"地方",v:"địa phương, vùng",e:"region, the provinces",p:"n"},
    {i:714,u:9,s:2,r:"せんそう",w:"戦争",v:"chiến tranh",e:"war",p:"n"},
    {i:715,u:9,s:2,r:"へいわ",w:"平和",v:"hòa bình",e:"peace",p:"n"},
    {i:716,u:10,s:1,r:"のぼる",w:"上る",v:"lên, leo lên; lên tới (con số)",e:"go up, reach",p:"v"},
    {i:717,u:10,s:1,r:"くだる",w:"下る",v:"đi xuống, xuống (dốc/sông)",e:"go down",p:"v"},
    {i:718,u:10,s:1,r:"すすむ",w:"進む",v:"tiến lên, tiến triển",e:"move forward, progress",p:"v"},
    {i:719,u:10,s:1,r:"すすめる",w:"進める",v:"đẩy tới, xúc tiến",e:"move forward, proceed",p:"v"},
    {i:720,u:10,s:1,r:"とおる",w:"通る",v:"đi qua; đỗ (kỳ thi)",e:"pass through; pass",p:"v"},
    {i:721,u:10,s:1,r:"とおす",w:"通す",v:"cho qua, xuyên qua; thông qua",e:"let through; pass (proposal)",p:"v"},
    {i:722,u:10,s:1,r:"こえる",w:"越える",v:"vượt qua, vượt quá",e:"cross, surpass",p:"v"},
    {i:723,u:10,s:1,r:"すぎる",w:"過ぎる",v:"đi qua; vượt quá",e:"pass by, elapse",p:"v"},
    {i:724,u:10,s:1,r:"すごす",w:"過ごす",v:"trải qua, sống (thời gian)",e:"spend (time)",p:"v"},
    {i:725,u:10,s:1,r:"うつる",w:"移る",v:"di chuyển, dời; lây (bệnh)",e:"move, relocate",p:"v"},
    {i:726,u:10,s:1,r:"うつす",w:"移す",v:"dời, chuyển; làm lây",e:"move, transmit",p:"v"},
    {i:727,u:10,s:1,r:"つれる",w:"連れる",v:"dẫn theo, đưa đi (người)",e:"take along",p:"v"},
    {i:728,u:10,s:1,r:"つたわる",w:"伝わる",v:"được truyền đạt; lan truyền",e:"be conveyed",p:"v"},
    {i:729,u:10,s:1,r:"よせる",w:"寄せる",v:"đưa lại gần, dồn lại",e:"move toward",p:"v"},
    {i:730,u:10,s:1,r:"あたえる",w:"与える",v:"cho, trao; gây (ảnh hưởng)",e:"give, provide",p:"v"},
    {i:731,u:10,s:1,r:"まく",w:"まく",v:"rắc, vãi, tưới",e:"scatter, sprinkle",p:"v"},
    {i:732,u:10,s:1,r:"むく",w:"向く",v:"hướng về; hợp với",e:"face; be suited for",p:"v"},
    {i:733,u:10,s:1,r:"むける",w:"向ける",v:"hướng tới, chĩa",e:"turn toward, aim",p:"v"},
    {i:734,u:10,s:1,r:"すすめる",w:"勧める",v:"khuyên, mời, khuyến khích",e:"recommend, offer",p:"v"},
    {i:735,u:10,s:1,r:"すすめる",w:"薦める",v:"tiến cử, giới thiệu",e:"recommend, suggest",p:"v"},
    {i:736,u:10,s:1,r:"まかせる",w:"任せる",v:"giao phó, để mặc",e:"entrust, leave to",p:"v"},
    {i:737,u:10,s:1,r:"まもる",w:"守る",v:"bảo vệ; tuân thủ, giữ",e:"protect; keep (a rule)",p:"v"},
    {i:738,u:10,s:1,r:"あらそう",w:"争う",v:"tranh cãi; tranh đua",e:"quarrel; compete",p:"v"},
    {i:739,u:10,s:1,r:"のぞむ",w:"望む",v:"mong muốn, mong ước",e:"wish",p:"v"},
    {i:740,u:10,s:1,r:"しんじる",w:"信じる",v:"tin, tin tưởng",e:"believe",p:"v"},
    {i:741,u:10,s:1,r:"つうじる",w:"通じる",v:"thông, hiểu được; dẫn tới",e:"be understood; lead to",p:"v"},
    {i:742,u:10,s:1,r:"あきる",w:"飽きる",v:"chán, ngấy",e:"be tired of",p:"v"},
    {i:743,u:10,s:1,r:"おもいつく",w:"思いつく",v:"nghĩ ra, chợt nghĩ ra",e:"think of",p:"v"},
    {i:744,u:10,s:1,r:"おもいやる",w:"思いやる",v:"quan tâm, thông cảm cho",e:"be considerate of",p:"v"},
    {i:745,u:10,s:1,r:"ねっちゅうする",w:"熱中する",v:"say mê, mải mê",e:"be absorbed in",p:"v"},
    {i:746,u:10,s:1,r:"くらす",w:"暮らす",v:"sinh sống",e:"live, get by",p:"v"},
    {i:747,u:10,s:1,r:"まく",w:"巻く",v:"cuốn, quấn",e:"wrap, coil",p:"v"},
    {i:748,u:10,s:1,r:"むすぶ",w:"結ぶ",v:"buộc, thắt; nối; ký kết",e:"tie; connect; conclude",p:"v"},
    {i:749,u:10,s:1,r:"すく",w:"空く",v:"trống, vắng; đói (bụng)",e:"be empty; become uncrowded",p:"v"},
    {i:750,u:10,s:1,r:"すませる",w:"済ませる",v:"làm xong, hoàn tất",e:"finish",p:"v"},
    {i:751,u:10,s:1,r:"できる",w:"出来る",v:"làm được; xong; có thể",e:"be able; be made; arise",p:"v"},
    {i:752,u:10,s:1,r:"きれる",w:"切れる",v:"cắt được; hết hạn; hết, đứt",e:"cut well; expire; run out",p:"v"},
    {i:753,u:10,s:1,r:"きらす",w:"切らす",v:"dùng hết, để hết sạch",e:"run out of",p:"v"},
    {i:754,u:10,s:2,r:"つたわる",w:"伝わる",v:"được lưu truyền, truyền lại",e:"be handed down",p:"v"},
    {i:755,u:10,s:2,r:"つたえる",w:"伝える",v:"truyền đạt, truyền lại, báo",e:"tell, convey",p:"v"},
    {i:756,u:10,s:2,r:"つづく",w:"続く",v:"tiếp tục, kéo dài",e:"continue (intr.)",p:"v"},
    {i:757,u:10,s:2,r:"つづける",w:"続ける",v:"tiếp tục (làm gì)",e:"continue (tr.)",p:"v"},
    {i:758,u:10,s:2,r:"つながる",w:"繋がる",v:"được kết nối, liên kết",e:"be connected",p:"v"},
    {i:759,u:10,s:2,r:"つなぐ",w:"繋ぐ",v:"nối, kết nối, buộc",e:"connect, tie",p:"v"},
    {i:760,u:10,s:2,r:"つなげる",w:"繋げる",v:"nối lại, kết nối",e:"connect (tr.)",p:"v"},
    {i:761,u:10,s:2,r:"のびる",w:"伸びる",v:"dài ra, vươn; kéo dài, phát triển",e:"grow, stretch",p:"v"},
    {i:762,u:10,s:2,r:"のばす",w:"伸ばす",v:"kéo dài, làm dài; vươn",e:"lengthen, stretch",p:"v"},
    {i:763,u:10,s:2,r:"のびる",w:"延びる",v:"được gia hạn, hoãn; kéo dài",e:"be postponed, prolonged",p:"v"},
    {i:764,u:10,s:2,r:"のばす",w:"延ばす",v:"hoãn, kéo dài (thời hạn)",e:"postpone, extend",p:"v"},
    {i:765,u:10,s:2,r:"かさなる",w:"重なる",v:"chồng lên; trùng nhau",e:"lie on top; coincide",p:"v"},
    {i:766,u:10,s:2,r:"かさねる",w:"重ねる",v:"xếp chồng; lặp lại",e:"pile up; repeat",p:"v"},
    {i:767,u:10,s:2,r:"ひろがる",w:"広がる",v:"mở rộng, lan ra",e:"widen, spread",p:"v"},
    {i:768,u:10,s:2,r:"ひろげる",w:"広げる",v:"trải rộng, mở rộng",e:"open out, widen",p:"v"},
    {i:769,u:10,s:2,r:"のる",w:"載る",v:"được đăng (báo), được ghi lên",e:"be published, be listed",p:"v"},
    {i:770,u:10,s:2,r:"のせる",w:"載せる",v:"đặt lên; đăng (báo)",e:"put on; publish",p:"v"},
    {i:771,u:10,s:2,r:"そろう",w:"揃う",v:"đầy đủ, đồng đều, tụ đủ",e:"be complete, gathered",p:"v"},
    {i:772,u:10,s:2,r:"そろえる",w:"揃える",v:"tập hợp đủ, làm cho đều",e:"make complete, arrange",p:"v"},
    {i:773,u:10,s:2,r:"まとまる",w:"まとまる",v:"được tập hợp, thống nhất, gọn lại",e:"be sorted out, united",p:"v"},
    {i:774,u:10,s:2,r:"まとめる",w:"まとめる",v:"tập hợp, tổng hợp, sắp xếp",e:"gather, organize",p:"v"},
    {i:775,u:10,s:2,r:"つく",w:"付く",v:"dính, bám; có thêm, đính kèm",e:"be attached; be gained",p:"v"},
    {i:776,u:10,s:2,r:"つける",w:"付ける",v:"gắn, đính; thêm vào; bôi",e:"attach; assign",p:"v"},
    {i:777,u:10,s:2,r:"たまる",w:"たまる",v:"tích lại, dồn lại, ứ đọng",e:"accumulate (intr.)",p:"v"},
    {i:778,u:10,s:2,r:"ためる",w:"ためる",v:"tích lũy, để dành",e:"accumulate, save up",p:"v"},
    {i:779,u:10,s:2,r:"まじる",w:"混じる",v:"lẫn vào, trộn lẫn",e:"be mingled with",p:"v"},
    {i:780,u:10,s:2,r:"まざる",w:"混ざる",v:"bị trộn lẫn",e:"be mixed together",p:"v"},
    {i:781,u:10,s:2,r:"まぜる",w:"混ぜる",v:"trộn, pha",e:"mix, blend",p:"v"},
    {i:782,u:10,s:2,r:"とける",w:"溶ける",v:"tan, tan chảy",e:"melt, dissolve (intr.)",p:"v"},
    {i:783,u:10,s:2,r:"とかす",w:"溶かす",v:"làm tan, hòa tan",e:"melt, dissolve (tr.)",p:"v"},
    {i:784,u:10,s:2,r:"ふくむ",w:"含む",v:"chứa, bao gồm",e:"contain, include",p:"v"},
    {i:785,u:10,s:2,r:"ふくめる",w:"含める",v:"bao gồm cả, tính cả",e:"include",p:"v"},
    {i:786,u:10,s:2,r:"ぬける",w:"抜ける",v:"rụng, tuột; xì (hơi); thiếu, sót",e:"fall out; leak; be missing",p:"v"},
    {i:787,u:10,s:2,r:"ぬく",w:"抜く",v:"rút ra, nhổ; bỏ qua; vượt",e:"pull out; skip; overtake",p:"v"},
    {i:788,u:10,s:2,r:"あらわれる",w:"現れる",v:"xuất hiện, hiện ra",e:"appear",p:"v"},
    {i:789,u:10,s:2,r:"あらわす",w:"現す",v:"làm hiện ra, thể hiện",e:"show (signs)",p:"v"},
    {i:790,u:10,s:2,r:"あらわれる",w:"表れる",v:"lộ ra, biểu lộ (ra mặt)",e:"show (on one's face)",p:"v"},
    {i:791,u:10,s:2,r:"あらわす",w:"表す",v:"biểu thị, biểu đạt",e:"express; represent",p:"v"},
    {i:792,u:10,s:2,r:"ちる",w:"散る",v:"rơi, rụng (hoa); tản ra",e:"fall; be scattered",p:"v"},
    {i:793,u:10,s:2,r:"ちらす",w:"散らす",v:"làm rơi rụng, làm tản",e:"spread, scatter",p:"v"},
    {i:794,u:10,s:2,r:"あける",w:"明ける",v:"(trời) sáng; (năm mới) sang; (mùa mưa) hết",e:"(dawn) comes; (year) starts",p:"v"},
    {i:795,u:10,s:2,r:"さす",w:"差す",v:"(nắng) chiếu; che (ô); nhỏ (thuốc mắt)",e:"(sun) shines; hold (umbrella)",p:"v"},
    {i:796,u:11,s:1,r:"パートナー",w:"パートナー",v:"đối tác; bạn đời/đồng hành",e:"partner",p:"k"},
    {i:797,u:11,s:1,r:"リーダー",w:"リーダー",v:"người lãnh đạo, thủ lĩnh",e:"leader",p:"k"},
    {i:798,u:11,s:1,r:"ボランティア",w:"ボランティア",v:"tình nguyện (viên)",e:"volunteer",p:"k"},
    {i:799,u:11,s:1,r:"コミュニケーション",w:"コミュニケーション",v:"giao tiếp, sự trao đổi",e:"communication",p:"k"},
    {i:800,u:11,s:1,r:"ユーモア",w:"ユーモア",v:"sự hài hước",e:"humor",p:"k"},
    {i:801,u:11,s:1,r:"ショック",w:"ショック",v:"sốc, cú sốc",e:"shock",p:"k"},
    {i:802,u:11,s:1,r:"ストレス",w:"ストレス",v:"căng thẳng, stress",e:"stress",p:"k"},
    {i:803,u:11,s:1,r:"バランス",w:"バランス",v:"sự cân bằng",e:"balance",p:"k"},
    {i:804,u:11,s:1,r:"レベル",w:"レベル",v:"trình độ, cấp độ",e:"level",p:"k"},
    {i:805,u:11,s:1,r:"アップ",w:"アップ",v:"tăng, nâng lên",e:"up, increase",p:"k"},
    {i:806,u:11,s:1,r:"ダウン",w:"ダウン",v:"giảm, hạ xuống",e:"down, reduction",p:"k"},
    {i:807,u:11,s:1,r:"プラス",w:"プラス",v:"cộng, thêm; điểm cộng, lợi",e:"plus, positive",p:"k"},
    {i:808,u:11,s:1,r:"マイナス",w:"マイナス",v:"trừ; điểm trừ, bất lợi",e:"minus, negative",p:"k"},
    {i:809,u:11,s:1,r:"イメージ",w:"イメージ",v:"hình ảnh, sự hình dung",e:"image",p:"k"},
    {i:810,u:11,s:1,r:"コンテスト",w:"コンテスト",v:"cuộc thi",e:"contest",p:"k"},
    {i:811,u:11,s:1,r:"マスコミ",w:"マスコミ",v:"truyền thông đại chúng",e:"mass media",p:"k"},
    {i:812,u:11,s:1,r:"プライバシー",w:"プライバシー",v:"sự riêng tư",e:"privacy",p:"k"},
    {i:813,u:11,s:1,r:"オフィス",w:"オフィス",v:"văn phòng",e:"office",p:"k"},
    {i:814,u:11,s:1,r:"ルール",w:"ルール",v:"quy tắc, luật lệ",e:"rule",p:"k"},
    {i:815,u:11,s:1,r:"マナー",w:"マナー",v:"phép lịch sự, cách cư xử",e:"manners",p:"k"},
    {i:816,u:11,s:1,r:"ミス",w:"ミス",v:"lỗi, sai sót",e:"mistake",p:"k"},
    {i:817,u:11,s:1,r:"スケジュール",w:"スケジュール",v:"lịch trình, kế hoạch",e:"schedule",p:"k"},
    {i:818,u:11,s:1,r:"タイトル",w:"タイトル",v:"tựa đề, tiêu đề",e:"title",p:"k"},
    {i:819,u:11,s:1,r:"テーマ",w:"テーマ",v:"chủ đề, đề tài",e:"theme, topic",p:"k"},
    {i:820,u:11,s:1,r:"ストーリー",w:"ストーリー",v:"cốt truyện",e:"story",p:"k"},
    {i:821,u:11,s:1,r:"ヒット",w:"ヒット",v:"thành công, ăn khách; cú đánh trúng",e:"hit",p:"k"},
    {i:822,u:11,s:1,r:"ブランド",w:"ブランド",v:"thương hiệu, hàng hiệu",e:"brand",p:"k"},
    {i:823,u:11,s:1,r:"レンタル",w:"レンタル",v:"sự cho thuê",e:"rental",p:"k"},
    {i:824,u:11,s:1,r:"リサイクル",w:"リサイクル",v:"tái chế",e:"recycling",p:"k"},
    {i:825,u:11,s:1,r:"ラベル",w:"ラベル",v:"nhãn",e:"label",p:"k"},
    {i:826,u:11,s:1,r:"タイプ",w:"タイプ",v:"kiểu, loại; gu",e:"type, sort",p:"k"},
    {i:827,u:11,s:1,r:"スタイル",w:"スタイル",v:"phong cách; dáng người",e:"style",p:"k"},
    {i:828,u:11,s:1,r:"セット",w:"セット",v:"bộ; cài đặt, chỉnh",e:"set, setting",p:"k"},
    {i:829,u:11,s:1,r:"ウイルス",w:"ウイルス",v:"vi-rút",e:"virus",p:"k"},
    {i:830,u:11,s:1,r:"ロボット",w:"ロボット",v:"người máy, rô-bốt",e:"robot",p:"k"},
    {i:831,u:11,s:1,r:"エネルギー",w:"エネルギー",v:"năng lượng",e:"energy",p:"k"},
    {i:832,u:11,s:1,r:"デジタル",w:"デジタル",v:"kỹ thuật số",e:"digital",p:"k"},
    {i:833,u:11,s:1,r:"マイク",w:"マイク",v:"micro",e:"microphone",p:"k"},
    {i:834,u:11,s:1,r:"ブレーキ",w:"ブレーキ",v:"phanh, thắng",e:"brake",p:"k"},
    {i:835,u:11,s:1,r:"ペンキ",w:"ペンキ",v:"sơn",e:"paint",p:"k"}
  ]
};
